import { useLocale, type AdminLanguage } from "../../../shared/ui/locale";

const copy = {
  fa: {
    locale: "fa-IR",
    saved: "کلاس ذخیره شد.",
    saveFailed: "ذخیره کلاس ناموفق بود.",
    deleted: "کلاس حذف شد.",
    deleteFailed: "حذف کلاس ناموفق بود.",
    booksSaved: "کتاب‌ها و دبیران کلاس ذخیره شد.",
    rosterSaved: "فهرست دانش‌آموزان کلاس ذخیره شد.",
    advisorSaved: "مشاور کلاس به‌روزرسانی شد.",
    newClass: "کلاس جدید",
    editClass: "ویرایش کلاس",
    editorDescription:
      "مشخصات کلاس را ثبت کنید؛ کتاب‌ها و دانش‌آموزان در مرحلهٔ بعد مدیریت می‌شوند.",
    loading: "در حال آماده‌سازی کلاس‌ها…",
    loadFailed: "دریافت اطلاعات کلاس ناموفق بود.",
    noAccess: "دسترسی مشاهده کلاس‌های آموزشی ندارید.",
    organizationClasses: "کلاس‌های سازمان",
    listDescription: "کتاب، دبیر، مشاور و ثبت‌نام را در یک جریان کنترل کنید.",
    active: "فعال",
    archived: "بایگانی",
    grade: (value: number) => `پایه ${value.toLocaleString("fa-IR")}`,
    advisor: "مشاور",
    notAssigned: "تعیین نشده",
    books: "کتاب",
    createClass: "ساخت کلاس",
    noClasses: "هنوز کلاسی برای این سازمان ساخته نشده است.",
    selectClass: "برای انتخاب کتاب، دبیر، مشاور و دانش‌آموزان، یک کلاس را انتخاب کنید.",
    students: "دانش‌آموز",
    edit: "ویرایش کلاس",
    classAdvisor: "مشاور کلاس",
    manageBooks: "مدیریت کتاب‌ها",
    manageStudents: "مدیریت دانش‌آموزان",
    loadingOptions: "در حال دریافت گزینه‌های کلاس…",
    booksAndTeachers: "کتاب‌ها و دبیران",
    eligibleStudents: "دانش‌آموزان واجد شرایط",
    deleteClass: "حذف کلاس",
    deleteTitle: "حذف کلاس؟",
    deleteDescription: (name: string) =>
      `کلاس «${name}» و فهرست کتاب‌ها و دانش‌آموزان آن حذف می‌شود.`,
    bookTeachersTitle: "کتاب‌ها و دبیران کلاس",
    bookTeachersDescription: "هر کتاب را انتخاب کنید و دبیر مسئول همان کتاب را تعیین کنید.",
    rosterTitle: "فهرست دانش‌آموزان کلاس",
    rosterDescription: "فقط دانش‌آموزان هم‌ساز با پایه، نوع آموزش و رشتهٔ کلاس نمایش داده می‌شوند.",
    advisorDescription: "یک مشاور یا مربی فعالِ همین سازمان را انتخاب کنید.",
    responsibleTeacher: "دبیر مسئول",
    selectTeacher: "انتخاب دبیر",
    inactiveBook: "این کتاب در کلاس فعال نیست.",
    cancel: "انصراف",
    saveBooks: "ذخیره کتاب‌ها",
    organization: "سازمان",
    selectOrganization: "سازمان را انتخاب کنید",
    schoolYear: "سال تحصیلی",
    className: "نام کلاس",
    classNamePlaceholder: "مثلاً دوازدهم تجربی الف",
    classCode: "کد کلاس",
    capacity: "ظرفیت",
    educationType: "نوع آموزش",
    track: "رشته",
    description: "توضیح",
    saveChanges: "ذخیره تغییرات",
    noAdvisor: "بدون مشاور",
    advisorLater: "بعداً تعیین می‌شود",
    advisorRole: "مشاور",
    coachRole: "مربی",
    saveAdvisor: "ذخیره مشاور",
    selected: (count: number) => `انتخاب‌شده: ${count.toLocaleString("fa-IR")}`,
    capacityLabel: (count: number) => `ظرفیت: ${count.toLocaleString("fa-IR")}`,
    unknownGrade: "پایه نامشخص",
    unknownTrack: "رشته نامشخص",
    enrolled: "ثبت‌نام",
    eligible: "واجد شرایط",
    noEligible: "دانش‌آموز واجد شرایطی برای این پروفایل آموزشی پیدا نشد.",
    saveRoster: "ذخیره فهرست",
  },
  en: {
    locale: "en-US",
    saved: "Class saved.",
    saveFailed: "Could not save the class.",
    deleted: "Class deleted.",
    deleteFailed: "Could not delete the class.",
    booksSaved: "Class books and teachers saved.",
    rosterSaved: "Class roster saved.",
    advisorSaved: "Class advisor updated.",
    newClass: "New class",
    editClass: "Edit class",
    editorDescription: "Enter the class details; books and students are managed in the next step.",
    loading: "Preparing classes…",
    loadFailed: "Could not load class information.",
    noAccess: "You do not have permission to view education classes.",
    organizationClasses: "Organization classes",
    listDescription: "Manage books, teachers, advisors, and enrollment in one flow.",
    active: "Active",
    archived: "Archived",
    grade: (value: number) => `Grade ${value.toLocaleString("en-US")}`,
    advisor: "Advisor",
    notAssigned: "Not assigned",
    books: "books",
    createClass: "Create class",
    noClasses: "No classes have been created for this organization.",
    selectClass: "Select a class to manage its books, teachers, advisor, and students.",
    students: "students",
    edit: "Edit class",
    classAdvisor: "Class advisor",
    manageBooks: "Manage books",
    manageStudents: "Manage students",
    loadingOptions: "Loading class options…",
    booksAndTeachers: "Books and teachers",
    eligibleStudents: "Eligible students",
    deleteClass: "Delete class",
    deleteTitle: "Delete class?",
    deleteDescription: (name: string) =>
      `The class “${name}” and its book and student roster will be deleted.`,
    bookTeachersTitle: "Class books and teachers",
    bookTeachersDescription: "Select each book and assign its responsible teacher.",
    rosterTitle: "Class student roster",
    rosterDescription:
      "Only students matching the class grade, education type, and track are shown.",
    advisorDescription: "Choose an active advisor or coach in this organization.",
    responsibleTeacher: "Responsible teacher",
    selectTeacher: "Select a teacher",
    inactiveBook: "This book is not active in the class.",
    cancel: "Cancel",
    saveBooks: "Save books",
    organization: "Organization",
    selectOrganization: "Select an organization",
    schoolYear: "School year",
    className: "Class name",
    classNamePlaceholder: "For example, Grade 12 Science A",
    classCode: "Class code",
    capacity: "Capacity",
    educationType: "Education type",
    track: "Track",
    description: "Description",
    saveChanges: "Save changes",
    noAdvisor: "No advisor",
    advisorLater: "Assign later",
    advisorRole: "Advisor",
    coachRole: "Coach",
    saveAdvisor: "Save advisor",
    selected: (count: number) => `Selected: ${count.toLocaleString("en-US")}`,
    capacityLabel: (count: number) => `Capacity: ${count.toLocaleString("en-US")}`,
    unknownGrade: "Unknown grade",
    unknownTrack: "Unknown track",
    enrolled: "Enrolled",
    eligible: "Eligible",
    noEligible: "No eligible students were found for this education profile.",
    saveRoster: "Save roster",
  },
} as const;

export function classesCopy(language: AdminLanguage) {
  return copy[language];
}

export function useClassesCopy() {
  return classesCopy(useLocale().language);
}
