import type { AdminLanguage } from "../../../shared/ui/locale";

const copy = {
  fa: {
    education: "آموزش",
    center: "مرکز آموزش",
    description:
      "وضعیت پوشش آموزشی را بررسی کنید، موارد نیازمند رسیدگی را به دانش‌آموز متصل کنید و سپس آزمون یا محتوای لازم را تکمیل کنید.",
    actions: "اقدام‌های آموزشی",
    createExam: "ساخت آزمون",
    createQuestion: "ساخت سؤال",
    importQuestion: "ورود سؤال",
    createQuiz: "ساخت آزمونک",
    recoveryRequests: "درخواست‌های بازیابی",
    catalog: "کاتالوگ کتاب‌های درسی و ورود گروهی",
    catalogDescription:
      "پس از آماده‌سازی کاتالوگ، پیش‌نمایش ورود را بررسی کنید و پیش‌نویس‌ها را ثبت کنید.",
    noSections: "هنوز بخشی برای نمایش وجود ندارد",
    loadingExamSnapshot: "در حال دریافت نمای آزمون…",
    examSnapshotFailed: "دریافت نمای آزمون ناموفق بود.",
    examMetrics: "شاخص‌های آزمون",
    frequentTopics: "موضوع‌های پرتکرار",
    exams: "آزمون",
    noTopics: "موضوعی ثبت نشده است.",
    needsAttention: "نیازمند توجه",
    noQuestions: "بدون سؤال",
    draft: "پیش‌نویس",
    noItems: "موردی ندارد.",
    operationsFilters: "فیلترهای پوشش آموزشی",
    grade: "پایه آموزشی",
    all: "همه",
    coverage: "پوشش آموزشی",
    completeProfile: "پرونده کامل",
    withoutPlan: "بدون برنامه",
    withoutResources: "بدون منبع",
    averageExam: "میانگین آزمون",
    exportOperations: "دریافت فایل CSV شاخص‌های فعلی",
    operations: "پایش پوشش آموزشی",
    operationsDescription:
      "بازه و پایه را انتخاب کنید، موارد نیازمند رسیدگی را باز کنید و نتیجه را برای پیگیری صادر کنید.",
    from: "از تاریخ",
    to: "تا تاریخ",
    clearFilters: "پاک‌سازی فیلترها",
    partialRange:
      "برای اعمال بازه، هر دو تاریخ را وارد کنید؛ تا آن زمان همه زمان‌ها نمایش داده می‌شود.",
    calculating: "در حال محاسبه شاخص‌های آموزشی…",
    operationsFailed: "شاخص‌های آموزشی دریافت نشد.",
    details: "جزئیات پوشش و صف‌های پیگیری",
    gradePrefix: "پایه",
    attentionDescription: "آزمون‌های بدون سؤال یا منتشرنشده را باز کنید و تکمیلشان کنید.",
    noPermissionDescription:
      "دسترسی شما به بخش‌های آموزش محدود است. در صورت نیاز با مدیر سیستم تماس بگیرید.",
  },
  en: {
    education: "Education",
    center: "Education center",
    description:
      "Review education coverage, connect items needing attention to students, then complete the required assessment or content.",
    actions: "Education actions",
    createExam: "Create exam",
    createQuestion: "Create question",
    importQuestion: "Import questions",
    createQuiz: "Create quiz",
    recoveryRequests: "Recovery requests",
    catalog: "Textbook catalog and bulk import",
    catalogDescription: "Preview the import after preparing the catalog, then save the drafts.",
    noSections: "There are no sections to show yet.",
    loadingExamSnapshot: "Loading exam snapshot…",
    examSnapshotFailed: "Could not load the exam snapshot.",
    examMetrics: "Exam metrics",
    frequentTopics: "Frequent topics",
    exams: "exams",
    noTopics: "No topics have been recorded.",
    needsAttention: "Needs attention",
    noQuestions: "No questions",
    draft: "Draft",
    noItems: "No items need attention.",
    operationsFilters: "Education coverage filters",
    grade: "Education grade",
    all: "All",
    coverage: "Education coverage",
    completeProfile: "Complete profile",
    withoutPlan: "Without plan",
    withoutResources: "Without resources",
    averageExam: "Average exam",
    exportOperations: "Download current metrics as CSV",
    operations: "Education coverage monitoring",
    operationsDescription:
      "Choose a date range and grade, open items needing attention, then export the result for follow-up.",
    from: "From date",
    to: "To date",
    clearFilters: "Clear filters",
    partialRange: "Enter both dates to apply a range. Until then, all dates are shown.",
    calculating: "Calculating education metrics…",
    operationsFailed: "Could not load education metrics.",
    details: "Coverage details and follow-up queues",
    gradePrefix: "Grade",
    attentionDescription: "Open exams without questions or publication and complete them.",
    noPermissionDescription:
      "Your access to education sections is limited. Contact a system administrator if you need access.",
  },
} as const;

export function educationCopy(language: AdminLanguage) {
  return copy[language];
}
