import { useLocale } from "../../../shared/ui/locale";

const copy = {
  fa: {
    loading: "در حال دریافت کاتالوگ آموزشی…",
    loadFailed: "کاتالوگ آموزشی دریافت نشد.",
    search: "جستجوی عنوان، کد یا دسته",
    allStates: "همه وضعیت‌ها",
    draft: "پیش‌نویس",
    published: "منتشرشده",
    archived: "بایگانی",
    books: "کتاب",
    grade: "پایه",
    editBook: "ویرایش کتاب",
    addBook: "افزودن کتاب",
    cancel: "انصراف",
    id: "شناسه",
    titleFa: "عنوان فارسی",
    schoolYear: "سال",
    category: "دسته",
    advanced: "تنظیمات تکمیلی",
    textbookCode: "کد کتاب",
    branch: "شاخه",
    track: "رشته",
    notes: "یادداشت",
    save: "ذخیره",
    bulkImport: "ورود گروهی JSON",
    bulkDescription: "ابتدا پیش‌نمایش بگیرید؛ همه ردیف‌ها پیش‌نویس می‌شوند.",
    jsonFile: "فایل JSON",
    bookArray: "آرایه کتاب‌ها",
    preview: "پیش‌نمایش",
    saveDrafts: "ثبت پیش‌نویس‌ها",
    noBooks: "کتابی با این فیلتر وجود ندارد.",
    edit: "ویرایش",
    audience: "مخاطب",
    publish: "انتشار",
    archive: "بایگانی",
    saved: "کتاب ذخیره شد.",
    saveFailed: "ذخیره کتاب ناموفق بود.",
    publishedSuccess: "کتاب منتشر شد.",
    publishFailed: "انتشار کتاب ناموفق بود.",
    archivedSuccess: "کتاب بایگانی شد.",
    archiveFailed: "بایگانی کتاب ناموفق بود.",
    audienceImpact: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} دانش‌آموز در محدوده این کتاب هستند.`,
    audienceFailed: "پیش‌نمایش مخاطبان کتاب ناموفق بود.",
    invalidJson: "JSON ورود معتبر نیست.",
    imported: "کتاب‌ها به‌صورت پیش‌نویس وارد شدند.",
    importFailed: "ورود کتاب‌ها ناموفق بود.",
    rowsReady: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} ردیف آماده پیش‌نمایش است.`,
    invalidFile: "فایل JSON باید یک آرایه از کتاب‌ها باشد.",
    importReady: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} ردیف آماده ورود است.`,
    row: (row: number, error: string) => `ردیف ${row}: ${error}`,
    newBookDefaults: {
      schoolYear: "1405-1406",
      branch: "نظری",
      track: "مشترک",
      category: "عمومی",
    },
  },
  en: {
    loading: "Loading education catalog…",
    loadFailed: "Could not load the education catalog.",
    search: "Search title, code, or category",
    allStates: "All states",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    books: "books",
    grade: "Grade",
    editBook: "Edit textbook",
    addBook: "Add textbook",
    cancel: "Cancel",
    id: "ID",
    titleFa: "Persian title",
    schoolYear: "School year",
    category: "Category",
    advanced: "Additional settings",
    textbookCode: "Textbook code",
    branch: "Branch",
    track: "Track",
    notes: "Notes",
    save: "Save",
    bulkImport: "Bulk JSON import",
    bulkDescription: "Preview the file first; every row will be created as a draft.",
    jsonFile: "JSON file",
    bookArray: "Book array",
    preview: "Preview",
    saveDrafts: "Save drafts",
    noBooks: "No textbooks match these filters.",
    edit: "Edit",
    audience: "Audience",
    publish: "Publish",
    archive: "Archive",
    saved: "Textbook saved.",
    saveFailed: "Could not save the textbook.",
    publishedSuccess: "Textbook published.",
    publishFailed: "Could not publish the textbook.",
    archivedSuccess: "Textbook archived.",
    archiveFailed: "Could not archive the textbook.",
    audienceImpact: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} students are in this textbook's audience.`,
    audienceFailed: "Could not preview the textbook audience.",
    invalidJson: "The import JSON is invalid.",
    imported: "Textbooks were imported as drafts.",
    importFailed: "Could not import the textbooks.",
    rowsReady: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} rows are ready to preview.`,
    invalidFile: "The JSON file must contain an array of textbooks.",
    importReady: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} rows are ready to import.`,
    row: (row: number, error: string) => `Row ${row}: ${error}`,
    newBookDefaults: {
      schoolYear: "2026-2027",
      branch: "General",
      track: "Common",
      category: "General",
    },
  },
} as const;

export function useEducationCatalogCopy() {
  const { language, profile } = useLocale();
  return { ...copy[language], locale: profile.locale };
}
