import { ArrowUpLeft, Send } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorState, LoadingState } from "../../components/ui";
import { apiClient } from "../../services/api-client";

type Request = { id: string; kind: string; title: string; details: string; requestedFor: string | null; status: "PENDING" | "APPROVED" | "REJECTED"; supervisorNote: string; organizationName?: string; createdAt: string | null };
const labels = { OUT_OF_DORM: "خروج از خوابگاه", OUT_OF_SCHOOL: "خروج از مدرسه", OTHER: "سایر" } as const;
export function PermissionRequestsPage() {
  const [rows, setRows] = useState<Request[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = () => { setState("loading"); void apiClient.request<Request[]>("GET", "/student/permission-requests").then((data) => { setRows(data); setState("ready"); }).catch(() => setState("error")); };
  useEffect(load, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setMessage(""); try { const row = await apiClient.request<Request, Record<string, string>>("POST", "/student/permission-requests", { kind: String(form.get("kind")), title: String(form.get("title")), details: String(form.get("details")), requestedFor: String(form.get("requestedFor") || "") }); setRows((old) => [row, ...old]); event.currentTarget.reset(); setMessage("درخواست شما برای بررسی ارسال شد."); } catch (error) { setMessage(error instanceof Error ? error.message : "ارسال درخواست ناموفق بود."); } finally { setBusy(false); } }
  return <section className="mx-auto grid max-w-3xl gap-5 pb-8"><header className="resource-library__header"><div><small>مجوزها</small><h1>درخواست مجوز</h1><p>برای خروج از خوابگاه، مدرسه یا هر مورد دیگر، درخواست خود را ثبت کنید.</p></div><Link to="/more" aria-label="بازگشت به بیشتر"><ArrowUpLeft /></Link></header><form onSubmit={submit} className="surface grid gap-3 p-4"><h2 className="font-semibold">درخواست جدید</h2><label className="grid gap-1 text-sm font-semibold">نوع درخواست<select name="kind" required defaultValue="OUT_OF_DORM" className="rounded-lg border border-ink/15 bg-paper p-3"><option value="OUT_OF_DORM">خروج از خوابگاه</option><option value="OUT_OF_SCHOOL">خروج از مدرسه</option><option value="OTHER">سایر</option></select></label><label className="grid gap-1 text-sm font-semibold">عنوان<input name="title" required maxLength={160} className="rounded-lg border border-ink/15 bg-paper p-3" placeholder="مثلا مراجعه پزشکی" /></label><label className="grid gap-1 text-sm font-semibold">زمان موردنیاز<input name="requestedFor" type="datetime-local" className="rounded-lg border border-ink/15 bg-paper p-3" /></label><label className="grid gap-1 text-sm font-semibold">توضیحات<textarea name="details" required maxLength={4000} rows={4} className="rounded-lg border border-ink/15 bg-paper p-3" placeholder="دلیل، مقصد و اطلاعات لازم را بنویسید." /></label><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-mint px-4 font-bold text-white disabled:opacity-60"><Send size={17} />{busy ? "در حال ارسال…" : "ارسال برای سرپرست"}</button>{message ? <p role="status" className="text-sm text-ink/70">{message}</p> : null}</form>{state === "loading" ? <LoadingState label="در حال دریافت درخواست‌ها" /> : null}{state === "error" ? <ErrorState message="دریافت درخواست‌ها ناموفق بود." onRetry={load} /> : null}{state === "ready" && !rows.length ? <EmptyState title="درخواستی ثبت نشده است." description="درخواست‌های شما و نتیجه بررسی در این بخش نمایش داده می‌شود." /> : null}{rows.map((row) => <article key={row.id} className="surface grid gap-2 p-4"><div className="flex items-start justify-between gap-3"><div><small>{row.organizationName || "سازمان"} · {labels[row.kind as keyof typeof labels] || row.kind}</small><h2 className="font-semibold">{row.title}</h2></div><strong className={row.status === "APPROVED" ? "text-mint" : row.status === "REJECTED" ? "text-red-700" : "text-amber-700"}>{row.status === "APPROVED" ? "تأیید شد" : row.status === "REJECTED" ? "رد شد" : "در انتظار بررسی"}</strong></div><p className="text-sm text-ink/70">{row.details}</p>{row.supervisorNote ? <p className="rounded-lg bg-paper p-2 text-sm"><strong>یادداشت سرپرست: </strong>{row.supervisorNote}</p> : null}</article>)}</section>;
}
