import type { AdminLanguage } from "../../../shared/ui/locale";

export const clockCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    tools: "ساعت و ابزارهای زمان",
    center: "مرکز زمان",
    close: "بستن",
    stayActive: "ابزارها پس از بستن این پنل همچنان فعال می‌مانند",
    clock: "ساعت",
    stopwatch: "کرنومتر",
    timer: "تایمر",
    alarms: "هشدارها",
    world: "جهانی",
    session: "نشست",
    activeAlarm: "هشدار فعال",
    timerFinished: "پایان",
    stopwatchRunning: "کرنومتر در حال اجرا",
    timerRunning: "تایمر در حال اجرا",
    timerPaused: "تایمر متوقف شده",
    timerFinishedTitle: "تایمر پایان یافته",
    nextAlarm: "هشدار بعدی",
    active: "فعال",
    inactive: "غیرفعال",
    idle: "کاربر غیرفعال است",
    runningAfterClose: "در حال اجرا — حتی با بستن پنل ادامه می‌دهد",
    pausedSaved: "مکث شده — زمان باقی‌مانده ذخیره شده است",
    timeFinished: "زمان تمام شد",
    ready: "آماده شروع",
    stop: "توقف",
    start: "شروع",
    continue: "ادامه",
    restart: "شروع دوباره",
    resetTimer: "ریست تایمر",
    resetStopwatch: "ریست کرنومتر",
    lap: "ثبت دور",
    lapLabel: "دور",
    customTime: "زمان دلخواه",
    minutes: "دقیقه",
    apply: "اعمال",
    alarm: "هشدار",
    snooze: "تعویق",
    dismiss: "بستن",
    hour: "ساعت",
    minute: "دقیقه",
    alarmTitle: "عنوان هشدار",
    add: "افزودن",
    repeat: "تکرار:",
    clear: "پاک کردن",
    everyDay: "هر روز",
    noAlarms: "هنوز هشداری تنظیم نشده است.",
    enabled: "فعال",
    disabled: "خاموش",
    deleteAlarm: "حذف هشدار",
    once: "یک‌بار",
    daysPerWeek: "روز در هفته",
    addWorldClock: "افزودن",
    deleteWorldClock: "حذف",
    currentSession: "این نشست",
    today: "امروز",
    sessionStart: "شروع نشست",
    lastExit: "آخرین خروج",
    activeSessionTime: "زمان فعال این نشست",
    clockFormat: "قالب ساعت",
    twelveHour: "۱۲ ساعته",
    twentyFourHour: "۲۴ ساعته",
    toolSounds: "صدای ابزارها",
    on: "روشن",
    off: "خاموش",
  },
  en: {
    tools: "Clock and time tools",
    center: "Time center",
    close: "Close",
    stayActive: "Tools keep running after this panel closes",
    clock: "Clock",
    stopwatch: "Stopwatch",
    timer: "Timer",
    alarms: "Alarms",
    world: "World",
    session: "Session",
    activeAlarm: "Alarm active",
    timerFinished: "Finished",
    stopwatchRunning: "Stopwatch running",
    timerRunning: "Timer running",
    timerPaused: "Timer paused",
    timerFinishedTitle: "Timer finished",
    nextAlarm: "Next alarm",
    active: "Active",
    inactive: "Inactive",
    idle: "User is idle",
    runningAfterClose: "Running — continues after this panel closes",
    pausedSaved: "Paused — remaining time is saved",
    timeFinished: "Time is up",
    ready: "Ready to start",
    stop: "Stop",
    start: "Start",
    continue: "Resume",
    restart: "Start again",
    resetTimer: "Reset timer",
    resetStopwatch: "Reset stopwatch",
    lap: "Record lap",
    lapLabel: "Lap",
    customTime: "Custom time",
    minutes: "minutes",
    apply: "Apply",
    alarm: "Alarm",
    snooze: "Snooze",
    dismiss: "Dismiss",
    hour: "Hour",
    minute: "Minute",
    alarmTitle: "Alarm title",
    add: "Add",
    repeat: "Repeat:",
    clear: "Clear",
    everyDay: "Every day",
    noAlarms: "No alarms have been set yet.",
    enabled: "On",
    disabled: "Off",
    deleteAlarm: "Delete alarm",
    once: "Once",
    daysPerWeek: "days a week",
    addWorldClock: "Add",
    deleteWorldClock: "Delete",
    currentSession: "This session",
    today: "Today",
    sessionStart: "Session started",
    lastExit: "Last exit",
    activeSessionTime: "Active time this session",
    clockFormat: "Clock format",
    twelveHour: "12-hour",
    twentyFourHour: "24-hour",
    toolSounds: "Tool sounds",
    on: "On",
    off: "Off",
  },
};

export const clockDays: Record<AdminLanguage, Array<{ id: number; label: string }>> = {
  fa: [
    { id: 6, label: "ش" },
    { id: 0, label: "ی" },
    { id: 1, label: "د" },
    { id: 2, label: "س" },
    { id: 3, label: "چ" },
    { id: 4, label: "پ" },
    { id: 5, label: "ج" },
  ],
  en: [
    { id: 0, label: "S" },
    { id: 1, label: "M" },
    { id: 2, label: "T" },
    { id: 3, label: "W" },
    { id: 4, label: "T" },
    { id: 5, label: "F" },
    { id: 6, label: "S" },
  ],
};

export const clockZones: Record<AdminLanguage, ReadonlyArray<readonly [string, string]>> = {
  fa: [
    ["تهران", "Asia/Tehran"],
    ["دبی", "Asia/Dubai"],
    ["استانبول", "Europe/Istanbul"],
    ["برلین", "Europe/Berlin"],
    ["لندن", "Europe/London"],
    ["نیویورک", "America/New_York"],
    ["لس‌آنجلس", "America/Los_Angeles"],
    ["تورنتو", "America/Toronto"],
    ["توکیو", "Asia/Tokyo"],
    ["سئول", "Asia/Seoul"],
    ["سنگاپور", "Asia/Singapore"],
    ["سیدنی", "Australia/Sydney"],
  ],
  en: [
    ["Tehran", "Asia/Tehran"],
    ["Dubai", "Asia/Dubai"],
    ["Istanbul", "Europe/Istanbul"],
    ["Berlin", "Europe/Berlin"],
    ["London", "Europe/London"],
    ["New York", "America/New_York"],
    ["Los Angeles", "America/Los_Angeles"],
    ["Toronto", "America/Toronto"],
    ["Tokyo", "Asia/Tokyo"],
    ["Seoul", "Asia/Seoul"],
    ["Singapore", "Asia/Singapore"],
    ["Sydney", "Australia/Sydney"],
  ],
};
