import type { AdminLanguage } from "../../../shared/ui/locale";

export const accessCopy = {
  fa: {
    organizationWorkspace: "مدیریت اعضا، نقش‌ها و ارتباط‌های سازمانی",
    totalMembers: "کل اعضا",
    active: "فعال",
    pending: "در انتظار",
    members: "اعضای سازمان",
    membersDescription: "افزودن، تغییر نقش و مدیریت وضعیت اعضا",
    searchMember: "جستجوی عضو…",
    close: "بستن",
    addMember: "افزودن عضو",
    selectUser: "انتخاب کاربر…",
    organizationRole: "نقش سازمانی",
    add: "افزودن",
    addMemberFailed: "افزودن عضو ناموفق بود.",
    membersFailed: "اعضا دریافت نشدند.",
    retry: "تلاش دوباره",
    noMemberSearch: "عضوی با این جستجو یافت نشد.",
    noMembers: "این سازمان هنوز عضوی ندارد.",
    noMembersHint: "برای شروع، اولین عضو را اضافه کنید.",
    inactive: "غیرفعال",
    noRole: "بدون نقش",
    suspend: "تعلیق",
    activate: "فعال‌سازی",
    removeMember: "حذف عضو",
    memberAdded: "عضو با نقش انتخاب‌شده به سازمان افزوده شد.",
    memberActivated: "عضویت فعال شد.",
    memberSuspended: "عضویت غیرفعال شد.",
    roleUpdated: "نقش سازمانی عضو به‌روزرسانی شد.",
    memberRemoved: "عضویت از سازمان حذف شد؛ حساب کاربری حفظ شده است.",
    relationships: "ارتباط‌ها",
    newRelationship: "ارتباط جدید",
    relationshipsDescription: "ارتباط بین کاربران و دانش‌آموزان",
    relationshipsFailed: "ارتباط‌ها دریافت نشدند.",
    noRelationships: "درخواست ارتباطی وجود ندارد.",
    noRelationshipsHint: "برای ایجاد ارتباط بین کاربران و دانش‌آموزان، ارتباط جدید بسازید.",
    organizationCreated: "سازمان ساخته شد.",
    organizationSaved: "اطلاعات سازمان ذخیره شد.",
    organizationArchived: "سازمان بایگانی شد.",
    organizationEnabled: "دسترسی سازمان فعال شد.",
    organizationDisabled: "دسترسی سازمان غیرفعال شد.",
    featuresUpdated: "قابلیت‌های سازمان به‌روزرسانی شد.",
    organizationFeatures: (name: string) => `قابلیت‌های ${name}`,
    featureDialogDescription: "قابلیت غیرفعال از منو و API اعضای این سازمان حذف می‌شود.",
    editOrganization: (name: string) => `ویرایش ${name}`,
    newOrganization: "سازمان جدید",
    editOrganizationDescription: "نام و نوع سازمان را به‌روزرسانی کنید.",
    newOrganizationDescription: "نام و نوع سازمان را وارد کنید.",
    organizationListTools: "ابزارهای فهرست سازمان‌ها",
    allOrganizations: "همه سازمان‌ها",
    archived: "بایگانی",
    searchOrganizations: "نام سازمان…",
    resultCount: (count: number, locale: string) => `${count.toLocaleString(locale)} نتیجه`,
    organizationList: "فهرست سازمان‌ها",
    organizationsFailed: "دریافت سازمان‌ها ناموفق بود.",
    clearSearch: "پاک‌کردن جستجو",
    organizationType: (type: string) =>
      ({
        SCHOOL: "مدرسه",
        ACADEMY: "آکادمی",
        COUNSELING_CENTER: "مرکز مشاوره",
        PRIVATE_PRACTICE: "مجموعه خصوصی",
        OTHER: "سایر",
      })[type] || type,
    enabledFeatureCount: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} قابلیت فعال`,
    selectedOrganizationDetails: "جزئیات سازمان انتخاب‌شده",
    enabledFeaturesOf: (enabled: number, total: number, locale: string) =>
      `${enabled.toLocaleString(locale)} قابلیت فعال از ${total.toLocaleString(locale)}`,
    manageFeatures: "مدیریت قابلیت‌ها",
    archivedOrganizationUnavailable: "سازمان بایگانی‌شده قابل مدیریت نیست.",
    selectOrganizationToManage: "یک سازمان را برای مدیریت اعضا انتخاب کنید.",
    userCreated: "حساب کاربری ساخته شد.",
    userStatusUpdated: "وضعیت حساب به‌روزرسانی شد.",
    userArchived: "حساب بایگانی شد.",
    ownershipTransferred: "مالکیت پلتفرم واگذار شد. حساب قبلی همچنان مدیر پلتفرم است.",
    accountsUpdated: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} حساب به‌روزرسانی شد.`,
    userAccessSaved: "مشخصات و دسترسی حساب ذخیره شد.",
    platformOwnership: "مالکیت پلتفرم",
    platformOwnershipDescription:
      "برای کارکنان، نقش محدود متناسب با کارشان انتخاب کنید. فقط هنگام نیاز واقعی، مدیر پلتفرم بسازید؛ سپس می‌توانید مالکیت را به آن حساب واگذار کنید.",
    userListTools: "ابزارهای فهرست کاربران",
    newUser: "کاربر جدید",
    newUserDescription: "حساب را از ابتدا با نقش و محدوده درست ایجاد کنید.",
    allAccounts: "همه حساب‌ها",
    roles: "نقش",
    searchUsers: "نام یا نام کاربری…",
    userResults: (visible: number, total: number, locale: string) =>
      `${visible.toLocaleString(locale)} نتیجه از ${total.toLocaleString(locale)}`,
    clearFilters: "پاک‌کردن فیلترها",
    userList: "فهرست کاربران",
    user: "کاربر",
    organization: "سازمان",
    platformLevel: "سطح پلتفرم",
    actions: "عملیات",
    relationshipAccepted: "درخواست ارتباط تأیید شد.",
    relationshipRejected: "درخواست ارتباط رد شد.",
    relationshipCreated: "ارتباط ایجاد شد.",
    relationshipRemoved: "ارتباط لغو شد.",
    guardianChangeAllowed: "محدودیت تغییر سرپرست لغو شد.",
    activeStatus: "فعال",
    inactiveStatus: "غیرفعال",
    archivedStatus: "بایگانی‌شده",
    allStatuses: "همه وضعیت‌ها",
    platformScope: "همه پلتفرم",
    organizationScope: "محدوده سازمان",
    accountStatus: "وضعیت حساب",
    username: "نام کاربری",
    password: "رمز اولیه (حداقل ۱۲ نویسه)",
    firstName: "نام",
    lastName: "نام خانوادگی",
    role: "نقش",
    organizationName: "نام سازمان",
    organizationKind: "نوع سازمان",
    selectOrganization: "انتخاب سازمان…",
    save: "ذخیره",
    saveChanges: "ذخیره تغییرات",
    cancel: "انصراف",
    createOrganization: "ساخت سازمان",
    createAccount: "ساخت حساب",
    loading: "در حال دریافت",
    editAccount: (name: string) => `ویرایش ${name}`,
    editAccountDescription: "مشخصات، نقش و محدوده دسترسی را یکجا ذخیره کنید.",
    protectedAccountHint: "برای حفظ دسترسی، نقش حساب فعلی و مالک پلتفرم از اینجا قابل تغییر نیست.",
    accountSaveFailed: "ویرایش حساب ناموفق بود.",
    accountCreateFailed: "ساخت حساب ناموفق بود.",
    usersFailed: "دریافت کاربران ناموفق بود.",
    usersDescription: "نقش و عملیات مجاز هر حساب در همان ردیف در دسترس است.",
    activateSelectedAccountsTitle: "فعال‌سازی حساب‌های انتخاب‌شده؟",
    activateSelectedAccountsDescription: (count: number, locale: string) =>
      `دسترسی ${count.toLocaleString(locale)} حساب دوباره فعال می‌شود.`,
    disableSelectedAccountsTitle: "غیرفعال‌کردن حساب‌های انتخاب‌شده؟",
    disableSelectedAccountsDescription: (count: number, locale: string) =>
      `دسترسی ${count.toLocaleString(locale)} حساب متوقف می‌شود.`,
    activateAccounts: "فعال‌سازی",
    disableAccounts: "غیرفعال‌کردن",
    platformOwner: "مالک پلتفرم",
    edit: "ویرایش",
    disableAccountTitle: "غیرفعال‌کردن حساب؟",
    disableAccountDescription: (name: string) => `دسترسی ${name} و نشست‌های فعال او متوقف می‌شود.`,
    disable: "غیرفعال",
    transferOwnershipFirst: "ابتدا واگذاری مالکیت",
    currentAccount: "حساب فعلی",
    archiveAccountTitle: "بایگانی حساب",
    archiveAccountDescription: (name: string) => `حساب ${name} بایگانی و نشست‌های آن بسته شود؟`,
    archive: "بایگانی",
    readOnly: "فقط مشاهده",
    rolesAndScopes: "نقش‌ها و محدوده‌ها",
    transferOwnershipTitle: "واگذاری مالکیت پلتفرم؟",
    transferOwnershipDescription: (name: string) =>
      `${name} مالک جدید می‌شود. حساب شما مدیر پلتفرم می‌ماند اما دیگر نمی‌تواند مدیر پلتفرم بسازد یا مالکیت را واگذار کند.`,
    transferOwnership: "واگذاری مالکیت",
    editAccountAccess: "ویرایش حساب و دسترسی",
    selectUserForDetails: "یک کاربر را برای مشاهده جزئیات انتخاب کنید.",
    deactivateOrganization: (name: string) => `غیرفعال‌کردن ${name}`,
    activateOrganization: (name: string) => `فعال‌کردن ${name}`,
    selectedWorkspace: "فضای کار انتخاب شده",
    openWorkspace: (name: string) => `بازکردن فضای کار ${name}`,
    selectWorkspace: (name: string) => `انتخاب ${name} به‌عنوان زمینه کاری`,
    archiveOrganizationTitle: "بایگانی سازمان",
    archiveOrganization: (name: string) => `بایگانی ${name}`,
    archiveOrganizationDescription: (name: string) =>
      `سازمان ${name} بایگانی شود؟ داده‌ها حذف نمی‌شوند.`,
    restoreOrganization: (name: string) => `بازیابی ${name}`,
    restoreOrganizationTitle: "بازیابی سازمان؟",
    restoreOrganizationDescription: (name: string) =>
      `سازمان ${name} و فضای مدیریتی آن دوباره فعال می‌شود.`,
    deactivateOrganizationTitle: "غیرفعال‌کردن سازمان؟",
    activateOrganizationTitle: "فعال‌کردن سازمان؟",
    deactivateOrganizationDescription: (name: string) =>
      `دسترسی سازمانی اعضای ${name} تا فعال‌سازی مجدد متوقف می‌شود.`,
    activateOrganizationDescription: (name: string) =>
      `دسترسی سازمانی اعضای ${name} دوباره فعال می‌شود.`,
    manageOrganizationFeatures: "مدیریت قابلیت‌های سازمان",
    organizationSaveFailed: "ذخیره سازمان ناموفق بود.",
    enableFeature: (name: string) => `فعال‌کردن ${name}`,
    disableFeature: (name: string) => `غیرفعال‌کردن ${name}`,
    disableFeatureTitle: (name: string) => `غیرفعال‌کردن ${name}؟`,
    disableFeatureDescription: (organization: string, name: string) =>
      `اعضای ${organization} فوراً دسترسی ${name} را در منو و API از دست می‌دهند.`,
    relationType: "نوع ارتباط",
    relatedUser: "کاربر مرتبط",
    student: "دانش‌آموز",
    selectStudent: "انتخاب دانش‌آموز…",
    relationCreateFailed: "ایجاد ارتباط ناموفق بود.",
    pendingRelationshipCount: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} درخواست در انتظار بررسی`,
    newRelationshipDescription: "فقط اعضای فعال همین سازمان برای ارتباط قابل انتخاب هستند.",
    memberRoleFor: (username: string) => `نقش ${username}`,
    suspendMembershipTitle: "غیرفعال‌کردن عضویت؟",
    suspendMembershipDescription: (name: string) =>
      `${name} تا فعال‌سازی مجدد به داده‌های این سازمان دسترسی ندارد.`,
    removeMembershipTitle: "حذف عضو از سازمان؟",
    removeMembershipDescription: (name: string) =>
      `عضویت ${name} حذف می‌شود؛ حساب کاربری او حذف نخواهد شد.`,
    removeMembership: "حذف عضویت",
    rejectRelationshipTitle: "رد درخواست ارتباط؟",
    rejectRelationshipDescription:
      "این درخواست رد می‌شود و برای ایجاد ارتباط، درخواست تازه‌ای لازم خواهد بود.",
    rejectRelationship: "رد درخواست",
    reject: "رد",
    approve: "تأیید",
    allowGuardianChange: "لغو محدودیت تغییر",
    revokeRelationshipTitle: "لغو ارتباط؟",
    revokeRelationshipDescription: (user: string, student: string) =>
      `ارتباط بین ${user} و ${student} لغو می‌شود.`,
    revokeRelationship: "لغو ارتباط",
    relationTypeLabel: (type: string) =>
      ({ GUARDIAN_OF: "سرپرست", ADVISOR_OF: "مشاور", TEACHER_OF: "دبیر", MENTOR_OF: "منتور" })[
        type
      ] || type,
    relationshipStatus: (status: string) =>
      ({ PENDING: "در انتظار بررسی", ACCEPTED: "تأییدشده", REJECTED: "ردشده" })[status] || status,
  },
  en: {
    organizationWorkspace: "Manage members, roles, and organization relationships",
    totalMembers: "Total members",
    active: "Active",
    pending: "Pending",
    members: "Organization members",
    membersDescription: "Add members, change roles, and manage membership status",
    searchMember: "Search members…",
    close: "Close",
    addMember: "Add member",
    selectUser: "Select a user…",
    organizationRole: "Organization role",
    add: "Add",
    addMemberFailed: "Couldn’t add the member.",
    membersFailed: "Couldn’t load members.",
    retry: "Try again",
    noMemberSearch: "No member matches this search.",
    noMembers: "This organization has no members yet.",
    noMembersHint: "Add the first member to get started.",
    inactive: "Inactive",
    noRole: "No role",
    suspend: "Suspend",
    activate: "Activate",
    removeMember: "Remove member",
    memberAdded: "The member was added with the selected role.",
    memberActivated: "Membership activated.",
    memberSuspended: "Membership suspended.",
    roleUpdated: "The member’s organization role was updated.",
    memberRemoved: "The membership was removed; the user account was kept.",
    relationships: "Relationships",
    newRelationship: "New relationship",
    relationshipsDescription: "Relationships between users and students",
    relationshipsFailed: "Couldn’t load relationships.",
    noRelationships: "There are no relationship requests.",
    noRelationshipsHint: "Create a relationship to connect users with students.",
    organizationCreated: "Organization created.",
    organizationSaved: "Organization details saved.",
    organizationArchived: "Organization archived.",
    organizationEnabled: "Organization access enabled.",
    organizationDisabled: "Organization access disabled.",
    featuresUpdated: "Organization features updated.",
    organizationFeatures: (name: string) => `${name} features`,
    featureDialogDescription:
      "A disabled feature is removed from this organization’s member menu and API access.",
    editOrganization: (name: string) => `Edit ${name}`,
    newOrganization: "New organization",
    editOrganizationDescription: "Update the organization name and type.",
    newOrganizationDescription: "Enter the organization name and type.",
    organizationListTools: "Organization list tools",
    allOrganizations: "All organizations",
    archived: "Archived",
    searchOrganizations: "Search organizations…",
    resultCount: (count: number, locale: string) => `${count.toLocaleString(locale)} results`,
    organizationList: "Organization list",
    organizationsFailed: "Couldn’t load organizations.",
    clearSearch: "Clear search",
    organizationType: (type: string) =>
      ({
        SCHOOL: "School",
        ACADEMY: "Academy",
        COUNSELING_CENTER: "Counseling center",
        PRIVATE_PRACTICE: "Private practice",
        OTHER: "Other",
      })[type] || type,
    enabledFeatureCount: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} enabled features`,
    selectedOrganizationDetails: "Selected organization details",
    enabledFeaturesOf: (enabled: number, total: number, locale: string) =>
      `${enabled.toLocaleString(locale)} enabled of ${total.toLocaleString(locale)}`,
    manageFeatures: "Manage features",
    archivedOrganizationUnavailable: "An archived organization cannot be managed.",
    selectOrganizationToManage: "Select an organization to manage its members.",
    userCreated: "User account created.",
    userStatusUpdated: "Account status updated.",
    userArchived: "Account archived.",
    ownershipTransferred:
      "Platform ownership transferred. The previous owner remains a platform administrator.",
    accountsUpdated: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} accounts updated.`,
    userAccessSaved: "User details and access saved.",
    platformOwnership: "Platform ownership",
    platformOwnershipDescription:
      "Give staff the narrowest role that fits their work. Create a platform administrator only when truly needed, then transfer ownership to that account.",
    userListTools: "User list tools",
    newUser: "New user",
    newUserDescription: "Create the account with the right role and scope from the start.",
    allAccounts: "All accounts",
    roles: "Roles",
    searchUsers: "Search name or username…",
    userResults: (visible: number, total: number, locale: string) =>
      `${visible.toLocaleString(locale)} of ${total.toLocaleString(locale)} results`,
    clearFilters: "Clear filters",
    userList: "User list",
    user: "User",
    organization: "Organization",
    platformLevel: "Platform level",
    actions: "Actions",
    relationshipAccepted: "Relationship request accepted.",
    relationshipRejected: "Relationship request rejected.",
    relationshipCreated: "Relationship created.",
    relationshipRemoved: "Relationship removed.",
    guardianChangeAllowed: "Guardian-change restriction removed.",
    activeStatus: "Active",
    inactiveStatus: "Inactive",
    archivedStatus: "Archived",
    allStatuses: "All statuses",
    platformScope: "Whole platform",
    organizationScope: "Organization scope",
    accountStatus: "Account status",
    username: "Username",
    password: "Initial password (at least 12 characters)",
    firstName: "First name",
    lastName: "Last name",
    role: "Role",
    organizationName: "Organization name",
    organizationKind: "Organization type",
    selectOrganization: "Select an organization…",
    save: "Save",
    saveChanges: "Save changes",
    cancel: "Cancel",
    createOrganization: "Create organization",
    createAccount: "Create account",
    loading: "Loading",
    editAccount: (name: string) => `Edit ${name}`,
    editAccountDescription: "Save identity, role, and access scope together.",
    protectedAccountHint:
      "To preserve access, the current account and platform owner role cannot be changed here.",
    accountSaveFailed: "Couldn’t update the account.",
    accountCreateFailed: "Couldn’t create the account.",
    usersFailed: "Couldn’t load users.",
    usersDescription: "Each account’s role and permitted actions are available in its row.",
    activateSelectedAccountsTitle: "Activate selected accounts?",
    activateSelectedAccountsDescription: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} accounts will regain access.`,
    disableSelectedAccountsTitle: "Disable selected accounts?",
    disableSelectedAccountsDescription: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} accounts will lose access.`,
    activateAccounts: "Activate",
    disableAccounts: "Disable",
    platformOwner: "Platform owner",
    edit: "Edit",
    disableAccountTitle: "Disable account?",
    disableAccountDescription: (name: string) =>
      `${name} and their active sessions will lose access.`,
    disable: "Disable",
    transferOwnershipFirst: "Transfer ownership first",
    currentAccount: "Current account",
    archiveAccountTitle: "Archive account",
    archiveAccountDescription: (name: string) => `Archive ${name} and close their sessions?`,
    archive: "Archive",
    readOnly: "Read only",
    rolesAndScopes: "Roles and scopes",
    transferOwnershipTitle: "Transfer platform ownership?",
    transferOwnershipDescription: (name: string) =>
      `${name} will become the new owner. Your account remains a platform administrator but can no longer create platform administrators or transfer ownership.`,
    transferOwnership: "Transfer ownership",
    editAccountAccess: "Edit account and access",
    selectUserForDetails: "Select a user to view their details.",
    deactivateOrganization: (name: string) => `Disable ${name}`,
    activateOrganization: (name: string) => `Enable ${name}`,
    selectedWorkspace: "Selected workspace",
    openWorkspace: (name: string) => `Open ${name} workspace`,
    selectWorkspace: (name: string) => `Set ${name} as the active workspace`,
    archiveOrganizationTitle: "Archive organization",
    archiveOrganization: (name: string) => `Archive ${name}`,
    archiveOrganizationDescription: (name: string) =>
      `Archive ${name}? Its data will not be deleted.`,
    restoreOrganization: (name: string) => `Restore ${name}`,
    restoreOrganizationTitle: "Restore organization?",
    restoreOrganizationDescription: (name: string) =>
      `${name} and its management workspace will be active again.`,
    deactivateOrganizationTitle: "Disable organization?",
    activateOrganizationTitle: "Enable organization?",
    deactivateOrganizationDescription: (name: string) =>
      `Members of ${name} will lose organization access until it is enabled again.`,
    activateOrganizationDescription: (name: string) =>
      `Members of ${name} will regain organization access.`,
    manageOrganizationFeatures: "Manage organization features",
    organizationSaveFailed: "Couldn’t save the organization.",
    enableFeature: (name: string) => `Enable ${name}`,
    disableFeature: (name: string) => `Disable ${name}`,
    disableFeatureTitle: (name: string) => `Disable ${name}?`,
    disableFeatureDescription: (organization: string, name: string) =>
      `Members of ${organization} will immediately lose ${name} in the menu and API.`,
    relationType: "Relationship type",
    relatedUser: "Related user",
    student: "Student",
    selectStudent: "Select a student…",
    relationCreateFailed: "Couldn’t create the relationship.",
    pendingRelationshipCount: (count: number, locale: string) =>
      `${count.toLocaleString(locale)} relationship requests pending`,
    newRelationshipDescription:
      "Only active members of this organization can be selected for a relationship.",
    memberRoleFor: (username: string) => `Role for ${username}`,
    suspendMembershipTitle: "Suspend membership?",
    suspendMembershipDescription: (name: string) =>
      `${name} cannot access this organization’s data until their membership is activated again.`,
    removeMembershipTitle: "Remove member from organization?",
    removeMembershipDescription: (name: string) =>
      `${name}’s membership will be removed, but their user account will remain.`,
    removeMembership: "Remove membership",
    rejectRelationshipTitle: "Reject relationship request?",
    rejectRelationshipDescription:
      "This request will be rejected and a new request is required to create the relationship.",
    rejectRelationship: "Reject request",
    reject: "Reject",
    approve: "Approve",
    allowGuardianChange: "Remove change restriction",
    revokeRelationshipTitle: "Revoke relationship?",
    revokeRelationshipDescription: (user: string, student: string) =>
      `The relationship between ${user} and ${student} will be revoked.`,
    revokeRelationship: "Revoke relationship",
    relationTypeLabel: (type: string) =>
      ({
        GUARDIAN_OF: "Guardian",
        ADVISOR_OF: "Advisor",
        TEACHER_OF: "Teacher",
        MENTOR_OF: "Mentor",
      })[type] || type,
    relationshipStatus: (status: string) =>
      ({ PENDING: "Pending review", ACCEPTED: "Approved", REJECTED: "Rejected" })[status] || status,
  },
} satisfies Record<AdminLanguage, object>;
