import type { AdminLanguage } from "../../../shared/ui/locale";

export const accessCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    organizationWorkspace: "مدیریت اعضا، نقش‌ها و ارتباط‌های سازمانی",
    totalMembers: "کل اعضا",
    active: "فعال",
    pending: "در انتظار",
    members: "اعضای سازمان",
    membersDescription: "افزودن، تغییر نقش و مدیریت وضعیت اعضا",
    searchMember: "جستجوی عضو…",
    close: "بستن",
    addMember: "افزودن عضو",
    user: "کاربر",
    selectUser: "انتخاب کاربر…",
    organizationRole: "نقش سازمانی",
    add: "افزودن",
    addMemberFailed: "افزودن عضو ناموفق بود.",
    membersFailed: "اعضا دریافت نشدند.",
    retry: "تلاش دوباره",
    noMemberSearch: "عضوی با این جستجو یافت نشد.",
    noMembers: "این سازمان هنوز عضوی ندارد.",
    noMembersHint: "برای شروع، اولین عضو را اضافه کنید.",
    inactive: "غیرفعال",
    noRole: "بدون نقش",
    suspend: "تعلیق",
    activate: "فعال‌سازی",
    removeMember: "حذف عضو",
    memberAdded: "عضو با نقش انتخاب‌شده به سازمان افزوده شد.",
    memberActivated: "عضویت فعال شد.",
    memberSuspended: "عضویت غیرفعال شد.",
    roleUpdated: "نقش سازمانی عضو به‌روزرسانی شد.",
    memberRemoved: "عضویت از سازمان حذف شد؛ حساب کاربری حفظ شده است.",
    relationships: "ارتباط‌ها",
    newRelationship: "ارتباط جدید",
    relationshipsDescription: "ارتباط بین کاربران و دانش‌آموزان",
    relationshipsFailed: "ارتباط‌ها دریافت نشدند.",
    noRelationships: "درخواست ارتباطی وجود ندارد.",
    noRelationshipsHint: "برای ایجاد ارتباط بین کاربران و دانش‌آموزان، ارتباط جدید بسازید.",
  },
  en: {
    organizationWorkspace: "Manage members, roles, and organization relationships",
    totalMembers: "Total members",
    active: "Active",
    pending: "Pending",
    members: "Organization members",
    membersDescription: "Add members, change roles, and manage membership status",
    searchMember: "Search members…",
    close: "Close",
    addMember: "Add member",
    user: "User",
    selectUser: "Select a user…",
    organizationRole: "Organization role",
    add: "Add",
    addMemberFailed: "Couldn’t add the member.",
    membersFailed: "Couldn’t load members.",
    retry: "Try again",
    noMemberSearch: "No member matches this search.",
    noMembers: "This organization has no members yet.",
    noMembersHint: "Add the first member to get started.",
    inactive: "Inactive",
    noRole: "No role",
    suspend: "Suspend",
    activate: "Activate",
    removeMember: "Remove member",
    memberAdded: "The member was added with the selected role.",
    memberActivated: "Membership activated.",
    memberSuspended: "Membership suspended.",
    roleUpdated: "The member’s organization role was updated.",
    memberRemoved: "The membership was removed; the user account was kept.",
    relationships: "Relationships",
    newRelationship: "New relationship",
    relationshipsDescription: "Relationships between users and students",
    relationshipsFailed: "Couldn’t load relationships.",
    noRelationships: "There are no relationship requests.",
    noRelationshipsHint: "Create a relationship to connect users with students.",
  },
};
