import type { AdminLanguage } from "../../../shared/ui/locale";

const copy = {
  fa: {
    organizationPlanning: "برنامه‌ریزی سازمانی",
    templates: "الگوهای برنامه",
    templatesDescription:
      "الگوهای منتشرشده را برای دانش‌آموزان اعمال کنید؛ ساخت الگوی تازه از برنامه‌های بازه فعلی انجام می‌شود.",
    goToPlanner: "رفتن به برنامه‌ریز",
    selectOrganization: "انتخاب سازمان",
    changeOrganization: "تغییر سازمان",
    loadingOrganizations: "در حال دریافت سازمان‌ها…",
    organizationsFailed: "فهرست سازمان‌ها دریافت نشد.",
    templatesUnavailable: "سازمان فعال برای الگوها در دسترس نیست.",
    templatesUnavailableDescription: "برای دیدن الگوهای برنامه، یک زمینه سازمانی فعال انتخاب کنید.",
    retry: "تلاش دوباره",
    view: "نمایش برنامه",
    day: "روز",
    week: "هفته",
    month: "ماه",
    list: "فهرست",
    previousRange: "بازه قبل",
    nextRange: "بازه بعد",
    searchActivities: "جستجوی فعالیت…",
    filterActive: "فیلتر فعال:",
    noStudent: "دانش‌آموزی انتخاب نشده است",
    activity: "فعالیت",
    activities: "فعالیت",
    minutes: "دقیقه",
    planStatus: "وضعیت برنامه",
    filter: "فیلتر",
    today: "امروز",
    rangeSummary: "خلاصه بازه",
    daysCount: (count: string) => `${count} روز`,
    activitiesCount: (count: string) => `${count} فعالیت`,
    hoursCount: (count: string) => `${count} ساعت`,
    testsCount: (count: string) => `${count} تست`,
    plansLoadFailed: "برنامه‌های این بازه دریافت نشدند؛ داده قبلی، در صورت وجود، حفظ شده است.",
    shareSucceeded: (copied: string, students: string, skipped: string) =>
      `${copied} برنامه برای ${students} دانش‌آموز کپی شد${skipped ? `؛ ${skipped} مورد موجود بدون تغییر ماند` : ""}.`,
    all: "همه",
    published: "منتشر",
    draft: "پیش‌نویس",
    incomplete: "ناتمام",
    planSettings: "تنظیمات برنامه روز",
    publishRange: "انتشار بازه",
    unpublishRange: "پیش‌نویس کردن بازه",
    importExportJson: "ورود / خروج JSON",
    shareHistory: "تاریخچه اشتراک‌گذاری",
    templateLibrary: "کتابخانه الگوهای برنامه",
    close: "بستن",
    commandPalette: "فرمان‌های برنامه‌ریز",
    commandSearch: "جستجوی فعالیت، تاریخ یا فرمان…",
    goToToday: "رفتن به امروز",
    viewMode: "نمای {mode}",
    results: "نتایج",
    noResults: "نتیجه‌ای پیدا نشد.",
    planDate: "تاریخ ISO",
    planTitle: "عنوان برنامه",
    dayLabel: "برچسب نمایش روز",
    persianDate: "تاریخ فارسی",
    jalaliId: "شناسه شمسی",
    status: "وضعیت",
    motivation: "پیام انگیزشی",
    save: "ذخیره",
    cancel: "انصراف",
    savePlanFailed: "ذخیره برنامه انجام نشد.",
    saveActivityFailed: "ذخیره فعالیت انجام نشد.",
    copyPlanFailed: "کپی برنامه انجام نشد.",
    startDaySetup: "شروع تنظیم روز",
    emptyDayHelp:
      "این روز هنوز عنوان یا پیام ندارد. یک متن آماده انتخاب کنید یا اطلاعات را خودتان وارد کنید.",
    startStudyDay: "شروع روز مطالعه",
    startReviewDay: "روز مرور",
    studyDayTitle: "برنامه مطالعاتی امروز",
    reviewDayTitle: "مرور و جمع‌بندی امروز",
    studyDayLabel: "روز مطالعه",
    reviewDayLabel: "روز مرور",
    studyDayMotivation: "با یک هدف کوچک و مشخص شروع کن؛ استمرار از کامل بودن مهم‌تر است.",
    reviewDayMotivation: "مطالب مهم را با آرامش مرور کن و نکات نیازمند تمرین را مشخص کن.",
    timeAndType: "زمان و نوع فعالیت",
    timeAndTypeHelp: "ابتدا بازه و نوع را مشخص کنید؛ مدت زمان به‌صورت خودکار محاسبه می‌شود.",
    start: "شروع",
    end: "پایان",
    type: "نوع",
    completeTimeRange: "بازه زمانی را کامل کنید",
    duration: "مدت: {duration}",
    educationGoal: "هدف آموزشی",
    educationGoalHelp: "عنوان کوتاه و درس، برنامه را برای دانش‌آموز قابل فهم می‌کند.",
    subject: "درس",
    subjectHelp: "کتاب‌های متناسب با پایه و رشته دانش‌آموز پیشنهاد می‌شوند.",
    title: "عنوان",
    relatedExam: "آزمون مرتبط",
    noExam: "بدون آزمون",
    openExamQuestionBank: "بازکردن بانک سؤال این آزمون",
    optionalDetails: "جزئیات تکمیلی (اختیاری)",
    pages: "صفحات",
    pagesPlaceholder: "مثلاً ۱۲ تا ۲۵",
    testCount: "تعداد تست",
    note: "یادداشت",
    notePlaceholder: "راهنمای لازم برای انجام فعالیت…",
    targetDate: "تاریخ مقصد",
    activityDetails: "جزئیات فعالیت",
    editPlan: "ویرایش برنامه روز",
    copyPlan: "کپی برنامه روز",
    deletePlan: "حذف برنامه روز",
    createActivityAt: "ساخت فعالیت در {time}",
    createActivityAtTime: "ساخت فعالیت در زمان {time}",
    noActivityToday: "این روز هنوز فعالیتی ندارد",
    noActivityTodayHelp: "از یک زمان مشخص شروع کنید یا تنظیمات روز را کامل کنید.",
    startPlanning: "شروع برنامه‌ریزی",
    daySettings: "تنظیمات روز",
    sharedTimeRuler: "خط‌کش زمان مشترک",
    moreTimeDetail: "جزئیات زمانی بیشتر",
    lessTimeDetail: "جزئیات زمانی کمتر",
    completed: "انجام‌شده",
    overdue: "تاخیر",
    planned: "برنامه‌ریزی",
    duplicateInThirtyMinutes: "تکثیر ۳۰ دقیقه بعد",
    deleteActivity: "حذف فعالیت",
    taskMenu: "منوی {title}",
    selectedActivities: "{count} فعالیت انتخاب شده",
    moveTime: "جابه‌جایی زمان",
    changePublication: "تغییر انتشار",
    clearSelection: "پاک کردن انتخاب",
    noTemplateOrganizations: "سازمانی برای الگوها وجود ندارد",
    templateOrganizationHelp:
      "الگوهای برنامه متعلق به یک سازمان هستند. سازمان موردنظر را انتخاب کنید.",
    copyPlanToAnotherDay: "کپی برنامه به روز دیگر",
    shareUnavailable: "برای این روز برنامه‌ای برای اشتراک‌گذاری وجود ندارد.",
    sharePlanWithStudent: "اشتراک برنامه با دانش‌آموز",
    planShareHistory: "تاریخچه اشتراک‌گذاری برنامه",
    loadingShareHistory: "در حال دریافت تاریخچه…",
    shareHistoryFailed: "دریافت تاریخچه اشتراک‌گذاری انجام نشد.",
    noShareHistory: "هنوز اشتراک‌گذاری گروهی ثبت نشده است.",
    dateRangeSeparator: "تا",
    shareHistorySummary: (targets: string, copied: string, skipped: string, policy: string) =>
      `${targets} دانش‌آموز · ${copied} کپی · ${skipped} بدون تغییر · ${policy}`,
    overwriteAllowed: "جایگزینی مجاز",
    keepExistingPlans: "حفظ برنامه موجود",
    destinationStudents: "دانش‌آموزان مقصد",
    destinationStudentsHelp: "فقط دانش‌آموزان در محدوده دسترسی نقش شما نمایش داده می‌شوند.",
    selectedCount: (count: string) => `${count} انتخاب`,
    searchDestinationStudents: "جستجوی دانش‌آموزان مقصد",
    searchDestinationStudentsPlaceholder: "جستجو بر اساس نام، پایه یا رشته…",
    grade: "پایه",
    educationType: "نوع آموزش",
    track: "رشته / مسیر",
    organization: "سازمان",
    selectAllVisible: "انتخاب همه نمایش‌داده‌شده",
    clearVisibleSelection: "برداشتن انتخاب‌های نمایش‌داده‌شده",
    clear: "پاک کردن",
    educationProfile: "پروفایل آموزشی",
    noStudentFound: "دانش‌آموزی پیدا نشد.",
    selectedDestinationStudents: "دانش‌آموزان انتخاب‌شده",
    removeStudentFromSelection: (name: string) => `حذف ${name} از انتخاب`,
    rangeAndConflict: "بازه و تعارض",
    rangeAndConflictHelp: "روزهای برنامه با همان فاصله زمانی به تاریخ مقصد منتقل می‌شوند.",
    readyShareRange: "بازه آماده اشتراک‌گذاری",
    onlyThisDay: "فقط همین روز",
    visibleRange: "بازه نمایش‌داده‌شده",
    sourcePlanFrom: "از برنامه مبدأ",
    sourcePlanTo: "تا برنامه مبدأ",
    targetRangeStart: "شروع بازه مقصد",
    replaceExistingPlans: "جایگزینی برنامه‌های موجود",
    replaceExistingPlansHelp:
      "به‌صورت پیش‌فرض برنامه موجود حفظ می‌شود. این گزینه فعالیت‌های برنامه مقصد را جایگزین می‌کند.",
    overwriteAcknowledgement: "متوجه هستم که برنامه‌های موجود مقصد جایگزین می‌شوند.",
    overwriteAcknowledgementHelp:
      "فعالیت‌های انجام‌شده همچنان توسط سرور محافظت می‌شوند و جایگزین نخواهند شد.",
    noOtherStudents: "دانش‌آموز دیگری در محدوده نقش فعال شما وجود ندارد.",
    sharePreview: "پیش‌نمایش اشتراک‌گذاری",
    previewDestinationPlans: (targets: string, plans: string) =>
      `${targets} دانش‌آموز · ${plans} برنامه مقصد`,
    previewExistingAndEmpty: (existing: string, empty: string) =>
      `${existing} برنامه موجود · ${empty} روز خالی`,
    previewConflicts: (time: string, exam: string, capacity: string) =>
      `${time} تداخل زمانی · ${exam} تداخل آزمون · ${capacity} روز فراتر از ظرفیت`,
    proposedLoad: (hours: string) => `بار پیشنهادی: ${hours} ساعت`,
    defaultExistingPlansHelp: "در حالت پیش‌فرض، برنامه‌های موجود بدون تغییر باقی می‌مانند.",
    invalidShareRange: "تاریخ شروع بازه باید پیش از تاریخ پایان باشد.",
    sharePlanFailed: "اشتراک‌گذاری برنامه انجام نشد.",
    sharePreviewFailed: "پیش‌نمایش اشتراک‌گذاری انجام نشد.",
    preview: "پیش‌نمایش",
    sharing: "در حال اشتراک…",
    sharePlan: "اشتراک برنامه",
    activityMoved: "زمان فعالیت جابه‌جا شد.",
    editDayDetails: "ویرایش مشخصات روز",
    createDayPlan: "ساخت برنامه روز",
    daySettingsForbidden: "دسترسی لازم برای تغییر تنظیمات این روز را ندارید.",
    loadDayPlanFailed: "دریافت برنامه روز انجام نشد.",
    createActivityFailed: "ساخت فعالیت انجام نشد.",
    delete: "حذف",
    newActivity: "فعالیت جدید",
    publishRangeConfirm: "انتشار برنامه‌های بازه؟",
    unpublishRangeConfirm: "پیش‌نویس کردن بازه؟",
    excelImportExport: "ورود و خروج Excel",
    transferPlansAndExams: "انتقال برنامه‌ها و آزمون‌های مرتبط",
    transferPlansAndExamsHelp: "ورود، اعتبارسنجی و خروجی استاندارد بازه",
    selectTemplateOrganization: "انتخاب سازمان برای الگوها",
    selectStudentToPlan: "برای مشاهده یا ساخت برنامه، ابتدا دانش‌آموز را از نوار بالا انتخاب کنید.",
    deleteActivityForbidden: "دسترسی حذف فعالیت را ندارید.",
    deleteActivityConfirm: "حذف فعالیت؟",
    deleteActivityDescription: "این فعالیت از برنامه دانش‌آموز حذف می‌شود.",
    createActivityForbidden: "دسترسی ساخت فعالیت را ندارید.",
    activityDuplicated: "فعالیت ۳۰ دقیقه بعد تکثیر شد.",
    duplicateActivityFailed: "تکثیر فعالیت انجام نشد.",
    moveActivityFailed: "جابجایی فعالیت ذخیره نشد و بازگردانده شد.",
    deletePlanForbidden: "دسترسی حذف برنامه را ندارید.",
    deletePlanConfirm: "حذف برنامه روز؟",
    deletePlanDescription: "همه فعالیت‌های این روز حذف می‌شوند.",
    editActivity: "ویرایش فعالیت",
    deleteDrawerActivityDescription: "این فعالیت از برنامه حذف می‌شود.",
    templateDayFallback: "برنامه روز",
    templateLibraryDescription:
      "الگوها فقط برای سازمان فعال ذخیره می‌شوند. پیش‌نویس زیر از {days} روزِ بازهٔ فعلی ساخته می‌شود و وضعیت انجام فعالیت‌ها را کپی نمی‌کند.",
    templateTitle: "عنوان الگو",
    templateDescription: "توضیح (اختیاری)",
    templateTags: "برچسب‌ها (با ویرگول جدا کنید)",
    templateTagsPlaceholder: "پایه دهم، ریاضی",
    templateSaveFailed: "ذخیره الگو انجام نشد. دوباره تلاش کنید.",
    creatingTemplate: "در حال ذخیره…",
    createTemplate: "ساخت پیش‌نویس از بازه فعلی",
    templateNeedsPlans: "برای ساخت الگو، ابتدا یک برنامه در بازه فعلی داشته باشید.",
    organizationTemplates: "الگوهای سازمان",
    templatesLoadFailed: "دریافت الگوها ناموفق بود.",
    noTemplates: "هنوز الگویی ساخته نشده است",
    version: "نسخه",
    templateDays: "روز",
    publish: "انتشار",
    applyToAudience: "اعمال برای مخاطبان",
    applyTemplate: "اعمال «{title}»",
    applyTemplateDescription:
      "برنامه‌های موجود حفظ می‌شوند؛ فقط روزهای خالی برای مخاطبان انتخاب‌شده ساخته می‌شوند.",
    applyStartDate: "شروع از تاریخ",
    templateAudience: "مخاطبان الگو",
    applyToStudents: "اعمال برای {count} دانش‌آموز",
    templateApplySucceeded: "{created} برنامه ایجاد شد.{skipped}",
    templateApplySkipped: " {count} برنامهٔ موجود بدون تغییر ماند.",
    templateApplyFailed: "اعمال الگو ناموفق بود.",
    templateState: {
      DRAFT: "پیش‌نویس",
      IN_REVIEW: "در انتظار بررسی",
      PUBLISHED: "منتشرشده",
      ARCHIVED: "بایگانی",
    },
  },
  en: {
    organizationPlanning: "Organization planning",
    templates: "Plan templates",
    templatesDescription:
      "Apply published templates to students. Create a new template from plans in the current range.",
    goToPlanner: "Open planner",
    selectOrganization: "Select organization",
    changeOrganization: "Change organization",
    loadingOrganizations: "Loading organizations…",
    organizationsFailed: "Could not load organizations.",
    templatesUnavailable: "An active organization is not available for templates.",
    templatesUnavailableDescription:
      "Select an active organization context to view plan templates.",
    retry: "Try again",
    view: "Plan view",
    day: "Day",
    week: "Week",
    month: "Month",
    list: "List",
    previousRange: "Previous range",
    nextRange: "Next range",
    searchActivities: "Search activities…",
    filterActive: "Active filter:",
    noStudent: "No student selected",
    activity: "activity",
    activities: "activities",
    minutes: "minutes",
    planStatus: "Plan status",
    filter: "Filter",
    today: "Today",
    rangeSummary: "Range summary",
    daysCount: (count: string) => `${count} days`,
    activitiesCount: (count: string) => `${count} activities`,
    hoursCount: (count: string) => `${count} hours`,
    testsCount: (count: string) => `${count} tests`,
    plansLoadFailed:
      "Plans for this range could not be loaded. Existing data is still shown when available.",
    shareSucceeded: (copied: string, students: string, skipped: string) =>
      `${copied} plans copied for ${students} students${skipped ? `; ${skipped} existing plans were left unchanged` : ""}.`,
    all: "All",
    published: "Published",
    draft: "Draft",
    incomplete: "Incomplete",
    planSettings: "Day plan settings",
    publishRange: "Publish range",
    unpublishRange: "Make range a draft",
    importExportJson: "Import / export JSON",
    shareHistory: "Share history",
    templateLibrary: "Plan template library",
    close: "Close",
    commandPalette: "Planner commands",
    commandSearch: "Search activities, dates, or commands…",
    goToToday: "Go to today",
    viewMode: "{mode} view",
    results: "Results",
    noResults: "No results found.",
    planDate: "ISO date",
    planTitle: "Plan title",
    dayLabel: "Day display label",
    persianDate: "Persian date",
    jalaliId: "Jalali identifier",
    status: "Status",
    motivation: "Motivational message",
    save: "Save",
    cancel: "Cancel",
    savePlanFailed: "Could not save the plan.",
    saveActivityFailed: "Could not save the activity.",
    copyPlanFailed: "Could not copy the plan.",
    startDaySetup: "Start day setup",
    emptyDayHelp:
      "This day has no title or message yet. Choose a starter or enter the details yourself.",
    startStudyDay: "Start study day",
    startReviewDay: "Review day",
    studyDayTitle: "Today's study plan",
    reviewDayTitle: "Today's review and recap",
    studyDayLabel: "Study day",
    reviewDayLabel: "Review day",
    studyDayMotivation:
      "Start with one small, clear goal; consistency matters more than perfection.",
    reviewDayMotivation: "Review key material calmly and mark the points that need practice.",
    timeAndType: "Time and activity type",
    timeAndTypeHelp: "Set the time range and type first; duration is calculated automatically.",
    start: "Start",
    end: "End",
    type: "Type",
    completeTimeRange: "Complete the time range",
    duration: "Duration: {duration}",
    educationGoal: "Learning goal",
    educationGoalHelp: "A concise title and subject make the plan clearer for the student.",
    subject: "Subject",
    subjectHelp: "Books matching the student's grade and track are suggested.",
    title: "Title",
    relatedExam: "Related exam",
    noExam: "No exam",
    openExamQuestionBank: "Open this exam's question bank",
    optionalDetails: "Additional details (optional)",
    pages: "Pages",
    pagesPlaceholder: "For example, 12–25",
    testCount: "Test count",
    note: "Note",
    notePlaceholder: "Guidance needed to complete this activity…",
    targetDate: "Target date",
    activityDetails: "Activity details",
    editPlan: "Edit day plan",
    copyPlan: "Copy day plan",
    deletePlan: "Delete day plan",
    createActivityAt: "Create activity at {time}",
    createActivityAtTime: "Create activity at time {time}",
    noActivityToday: "This day has no activities yet",
    noActivityTodayHelp: "Start at a specific time or finish the day setup.",
    startPlanning: "Start planning",
    daySettings: "Day settings",
    sharedTimeRuler: "Shared time ruler",
    moreTimeDetail: "More time detail",
    lessTimeDetail: "Less time detail",
    completed: "Completed",
    overdue: "Overdue",
    planned: "Planned",
    duplicateInThirtyMinutes: "Duplicate 30 minutes later",
    deleteActivity: "Delete activity",
    taskMenu: "Menu for {title}",
    selectedActivities: "{count} activities selected",
    moveTime: "Move time",
    changePublication: "Change publication",
    clearSelection: "Clear selection",
    noTemplateOrganizations: "No organizations are available for templates",
    templateOrganizationHelp:
      "Plan templates belong to one organization. Choose the relevant organization.",
    copyPlanToAnotherDay: "Copy plan to another day",
    shareUnavailable: "There is no plan on this day to share.",
    sharePlanWithStudent: "Share plan with students",
    planShareHistory: "Plan share history",
    loadingShareHistory: "Loading share history…",
    shareHistoryFailed: "Could not load the share history.",
    noShareHistory: "No group plan shares have been recorded yet.",
    dateRangeSeparator: "to",
    shareHistorySummary: (targets: string, copied: string, skipped: string, policy: string) =>
      `${targets} students · ${copied} copied · ${skipped} unchanged · ${policy}`,
    overwriteAllowed: "Overwrite allowed",
    keepExistingPlans: "Keep existing plans",
    destinationStudents: "Destination students",
    destinationStudentsHelp: "Only students within your active role's access scope are shown.",
    selectedCount: (count: string) => `${count} selected`,
    searchDestinationStudents: "Search destination students",
    searchDestinationStudentsPlaceholder: "Search by name, grade, or track…",
    grade: "Grade",
    educationType: "Education type",
    track: "Track",
    organization: "Organization",
    selectAllVisible: "Select all visible",
    clearVisibleSelection: "Clear visible selection",
    clear: "Clear",
    educationProfile: "Education profile",
    noStudentFound: "No students found.",
    selectedDestinationStudents: "Selected destination students",
    removeStudentFromSelection: (name: string) => `Remove ${name} from selection`,
    rangeAndConflict: "Range and conflicts",
    rangeAndConflictHelp: "Plan days keep the same intervals when they move to the target date.",
    readyShareRange: "Ready share range",
    onlyThisDay: "This day only",
    visibleRange: "Visible range",
    sourcePlanFrom: "Source plan from",
    sourcePlanTo: "Source plan to",
    targetRangeStart: "Target range start",
    replaceExistingPlans: "Replace existing plans",
    replaceExistingPlansHelp:
      "Existing plans are kept by default. This option replaces activities in the destination plans.",
    overwriteAcknowledgement: "I understand that destination plans will be replaced.",
    overwriteAcknowledgementHelp:
      "Completed activities remain protected by the server and will not be replaced.",
    noOtherStudents: "No other students are available within your active role's scope.",
    sharePreview: "Share preview",
    previewDestinationPlans: (targets: string, plans: string) =>
      `${targets} students · ${plans} destination plans`,
    previewExistingAndEmpty: (existing: string, empty: string) =>
      `${existing} existing plans · ${empty} empty days`,
    previewConflicts: (time: string, exam: string, capacity: string) =>
      `${time} time conflicts · ${exam} exam conflicts · ${capacity} over-capacity days`,
    proposedLoad: (hours: string) => `Proposed load: ${hours} hours`,
    defaultExistingPlansHelp: "By default, existing plans remain unchanged.",
    invalidShareRange: "The range start date must be before the end date.",
    sharePlanFailed: "Could not share the plan.",
    sharePreviewFailed: "Could not preview the plan share.",
    preview: "Preview",
    sharing: "Sharing…",
    sharePlan: "Share plan",
    activityMoved: "Activity time moved.",
    editDayDetails: "Edit day details",
    createDayPlan: "Create day plan",
    daySettingsForbidden: "You do not have access to change this day's settings.",
    loadDayPlanFailed: "Could not load the day plan.",
    createActivityFailed: "Could not create the activity.",
    delete: "Delete",
    newActivity: "New activity",
    publishRangeConfirm: "Publish plans in this range?",
    unpublishRangeConfirm: "Make plans in this range drafts?",
    excelImportExport: "Excel import and export",
    transferPlansAndExams: "Transfer related plans and exams",
    transferPlansAndExamsHelp: "Import, validate, and export the selected range.",
    selectTemplateOrganization: "Choose an organization for templates",
    selectStudentToPlan: "Choose a student from the bar above before viewing or creating a plan.",
    deleteActivityForbidden: "You do not have access to delete activities.",
    deleteActivityConfirm: "Delete activity?",
    deleteActivityDescription: "This activity will be removed from the student's plan.",
    createActivityForbidden: "You do not have access to create activities.",
    activityDuplicated: "Activity duplicated 30 minutes later.",
    duplicateActivityFailed: "Could not duplicate the activity.",
    moveActivityFailed: "The activity move could not be saved and was reverted.",
    deletePlanForbidden: "You do not have access to delete plans.",
    deletePlanConfirm: "Delete day plan?",
    deletePlanDescription: "All activities on this day will be deleted.",
    editActivity: "Edit activity",
    deleteDrawerActivityDescription: "This activity will be removed from the plan.",
    templateDayFallback: "Day plan",
    templateLibraryDescription:
      "Templates are stored for the active organization only. This draft uses {days} days from the current range and does not copy task completion status.",
    templateTitle: "Template title",
    templateDescription: "Description (optional)",
    templateTags: "Tags (separate with commas)",
    templateTagsPlaceholder: "Grade 10, Mathematics",
    templateSaveFailed: "Could not save the template. Try again.",
    creatingTemplate: "Saving…",
    createTemplate: "Create draft from current range",
    templateNeedsPlans: "Add a plan in the current range before creating a template.",
    organizationTemplates: "Organization templates",
    templatesLoadFailed: "Could not load templates.",
    noTemplates: "No templates have been created yet",
    version: "Version",
    templateDays: "days",
    publish: "Publish",
    applyToAudience: "Apply to audience",
    applyTemplate: "Apply “{title}”",
    applyTemplateDescription:
      "Existing plans are preserved; only empty days are created for the selected audience.",
    applyStartDate: "Start from date",
    templateAudience: "Template audience",
    applyToStudents: "Apply to {count} students",
    templateApplySucceeded: "{created} plans created.{skipped}",
    templateApplySkipped: " {count} existing plans were left unchanged.",
    templateApplyFailed: "Could not apply the template.",
    templateState: {
      DRAFT: "Draft",
      IN_REVIEW: "In review",
      PUBLISHED: "Published",
      ARCHIVED: "Archived",
    },
  },
} as const;

export function plannerCopy(language: AdminLanguage) {
  return copy[language];
}

export function plannerModeLabel(mode: "day" | "week" | "month" | "list", language: AdminLanguage) {
  return plannerCopy(language)[mode];
}

export function plannerFilterLabel(
  filter: "all" | "published" | "draft" | "incomplete",
  language: AdminLanguage,
) {
  const labels = {
    fa: {
      all: "همه برنامه‌ها",
      published: "فقط منتشرشده",
      draft: "فقط پیش‌نویس",
      incomplete: "فعالیت‌های انجام‌نشده",
    },
    en: {
      all: "All plans",
      published: "Published only",
      draft: "Drafts only",
      incomplete: "Incomplete activities",
    },
  } as const;
  return labels[language][filter];
}

const taskTypes = {
  fa: {
    study: "مطالعه",
    review: "مرور",
    test: "تست",
    class: "کلاس",
    prayer: "نماز",
    meal: "وعده غذایی",
    break: "استراحت",
    exam: "آزمون",
  },
  en: {
    study: "Study",
    review: "Review",
    test: "Test",
    class: "Class",
    prayer: "Prayer",
    meal: "Meal",
    break: "Break",
    exam: "Exam",
  },
} as const;

export function plannerTaskTypeLabel(type: string, language: AdminLanguage) {
  return taskTypes[language][type as keyof (typeof taskTypes)["fa"]] ?? type;
}
