import type { AdminLanguage } from "../../../shared/ui/locale";

export const notificationCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    center: "اعلان‌های مدیر",
    centerDescription: "پیام‌ها، آزمون‌ها و اطلاعیه‌های بارگذاری‌شده را در همین‌جا پیگیری کنید.",
    inbox: "صندوق پیگیری",
    inboxDescription: "مشکلات و ریکاوری‌ها از همین صفحه قابل پاسخ و بستن هستند.",
    loadFailed: "دریافت اعلان‌ها ناموفق بود.",
    inboxFailed: "صندوق پیگیری دریافت نشد.",
    allRead: "همه اعلان‌ها خوانده شده‌اند.",
    noMatch: "اعلانی مطابق فیلتر پیدا نشد.",
    none: "اعلانی وجود ندارد.",
    noItems: "مورد فعالی برای این دانش‌آموز وجود ندارد.",
    markAll: "خواندن همه",
    refresh: "تازه‌سازی اعلان‌ها",
    search: "جستجوی اعلان‌ها",
    searchPlaceholder: "جستجو در اعلان‌های بارگذاری‌شده",
    type: "نوع اعلان",
    allTypes: "همه نوع‌ها",
    message: "پیام",
    exam: "آزمون",
    lesson: "برنامه",
    announcement: "اطلاعیه",
    readState: "وضعیت خواندن اعلان‌ها",
    all: "همه",
    unread: "خوانده‌نشده",
    more: "نمایش اعلان‌های بیشتر",
    unreadDot: "خوانده‌نشده",
    operational: "عملیاتی",
    notifications: "اعلان‌ها",
    notification: "اعلان",
    unreadCount: "خوانده‌نشده",
    noNew: "اعلان جدیدی وجود ندارد.",
    viewCenter: "مشاهده مرکز اعلان‌ها",
    retry: "تلاش دوباره",
    deviceSettings: "تنظیمات دستگاه",
    notificationSound: "صدای اعلان",
    messageSound: "صدای پیام",
    enabled: "فعال",
    disabled: "غیرفعال",
    notificationSections: "بخش اعلان‌ها",
    followUp: "پیگیری",
    settingsTitle: "اعلان سیستمی و صدا",
    savePreferenceFailed: "ذخیره ترجیح اعلان انجام نشد.",
    notificationFor: "اعلان",
    loadingSettings: "در حال دریافت تنظیمات اعلان",
    settingsFailed: "تنظیمات اعلان دریافت نشد",
    operationFailed: "عملیات اعلان ناموفق بود.",
    pushUnsupported: "این مرورگر Push را پشتیبانی نمی‌کند.",
    pushServerMissing: "کلیدهای Web Push روی سرور تنظیم نشده‌اند.",
    pushPermissionDenied: "اجازه اعلان در تنظیمات مرورگر مسدود شده است.",
    pushEnabled: "اعلان سیستمی این دستگاه فعال است.",
    pushPermissionPending:
      "منتظر اجازه مرورگر: برای ادامه، فعال‌سازی را بزنید و اجازه اعلان را تأیید کنید.",
    pushDisabled: "اعلان سیستمی این دستگاه غیرفعال است؛ برای دریافت در پس‌زمینه آن را فعال کنید.",
    disablePush: "غیرفعال‌کردن Push",
    enablePush: "فعال‌کردن اعلان سیستمی",
    testPush: "ارسال اعلان آزمایشی",
    testSound: "آزمایش صدا",
    pushDisabledSuccess: "اعلان سیستمی این دستگاه غیرفعال شد.",
    pushEnabledSuccess: "اعلان سیستمی این دستگاه فعال شد.",
    pushTestSuccess: "درخواست اعلان آزمایشی ثبت شد؛ دریافت آن را روی همین دستگاه بررسی کنید.",
    messages: "پیام‌ها",
    exams: "آزمون‌ها",
    lessons: "برنامه و درس",
    announcements: "اطلاعیه‌ها",
    deliveryStatus: "وضعیت تحویل روی مرورگرها و دستگاه‌ها",
    thisDevice: "این دستگاه",
    deliveryErrors: "خطای تحویل",
    deliverySuccess: "تحویل موفق:",
    waitingFirstDelivery: "در انتظار نخستین تحویل",
    lastActivity: "آخرین فعالیت:",
    unknownBrowser: "مرورگر ناشناس",
    unknownDevice: "دستگاه ناشناس",
    activityIssue: "مشکل فعالیت",
    untitledActivity: "فعالیت بدون عنوان",
    latestAdvisorReply: "آخرین پاسخ مشاور:",
    closeResponse: "بستن پاسخ",
    respond: "رسیدگی و پاسخ",
    responsePlaceholder: "یادداشت یا پاسخ مشاور… در صورت ثبت، برای دانش‌آموز هم اعلان می‌شود.",
    replyKeepOpen: "پاسخ و باز نگه‌داشتن",
    resolved: "حل شد",
    dismissReport: "رد گزارش",
    recoveryRequest: "درخواست ریکاوری",
    plan: "برنامه",
    closeHandling: "بستن رسیدگی",
    handle: "رسیدگی",
    recoveryMessagePlaceholder: "پیام برای دانش‌آموز بعد از تأیید ریکاوری…",
    resolveAndNotify: "حل و اطلاع‌رسانی",
    rejectRequest: "رد درخواست",
    rejectionHint:
      "رد درخواست در API v1 اعلان جداگانه‌ای برای دانش‌آموز ارسال نمی‌کند؛ حل کردن همراه پیام، اطلاع‌رسانی می‌شود.",
    followUpItem: "مورد پیگیری",
    time: "زمان",
    until: "تا",
    reviewInterval: "فاصله مرور",
    days: "روز",
  },
  en: {
    center: "Admin notifications",
    centerDescription: "Follow loaded messages, exams, and announcements here.",
    inbox: "Follow-up inbox",
    inboxDescription: "Respond to and resolve issues and recovery requests from this workspace.",
    loadFailed: "Couldn’t load notifications.",
    inboxFailed: "Couldn’t load the follow-up inbox.",
    allRead: "All notifications are read.",
    noMatch: "No notification matches these filters.",
    none: "There are no notifications.",
    noItems: "There are no active items for this student.",
    markAll: "Mark all read",
    refresh: "Refresh notifications",
    search: "Search notifications",
    searchPlaceholder: "Search loaded notifications",
    type: "Notification type",
    allTypes: "All types",
    message: "Message",
    exam: "Exam",
    lesson: "Plan",
    announcement: "Announcement",
    readState: "Read status",
    all: "All",
    unread: "Unread",
    more: "Show more notifications",
    unreadDot: "Unread",
    operational: "actionable",
    notifications: "Notifications",
    notification: "Notification",
    unreadCount: "unread",
    noNew: "There are no new notifications.",
    viewCenter: "View notification center",
    retry: "Try again",
    deviceSettings: "Device settings",
    notificationSound: "Notification sound",
    messageSound: "Message sound",
    enabled: "Enabled",
    disabled: "Disabled",
    notificationSections: "Notification sections",
    followUp: "Follow-up",
    settingsTitle: "System notifications and sound",
    savePreferenceFailed: "Couldn’t save notification preference.",
    notificationFor: "Notification",
    loadingSettings: "Loading notification settings",
    settingsFailed: "Couldn’t load notification settings",
    operationFailed: "Notification action failed.",
    pushUnsupported: "This browser does not support push notifications.",
    pushServerMissing: "Web Push keys are not configured on the server.",
    pushPermissionDenied: "Notification permission is blocked in browser settings.",
    pushEnabled: "System notifications are enabled on this device.",
    pushPermissionPending:
      "Waiting for browser permission: enable notifications, then confirm the browser prompt.",
    pushDisabled:
      "System notifications are disabled on this device; enable them for background delivery.",
    disablePush: "Disable Push",
    enablePush: "Enable system notifications",
    testPush: "Send test notification",
    testSound: "Test sound",
    pushDisabledSuccess: "System notifications were disabled for this device.",
    pushEnabledSuccess: "System notifications were enabled for this device.",
    pushTestSuccess: "A test notification was requested; check delivery on this device.",
    messages: "Messages",
    exams: "Exams",
    lessons: "Plans and lessons",
    announcements: "Announcements",
    deliveryStatus: "Delivery status across browsers and devices",
    thisDevice: "This device",
    deliveryErrors: "delivery errors",
    deliverySuccess: "Delivered:",
    waitingFirstDelivery: "Waiting for first delivery",
    lastActivity: "Last activity:",
    unknownBrowser: "Unknown browser",
    unknownDevice: "Unknown device",
    activityIssue: "Activity issue",
    untitledActivity: "Untitled activity",
    latestAdvisorReply: "Latest advisor reply:",
    closeResponse: "Close response",
    respond: "Review and respond",
    responsePlaceholder: "Advisor note or response… when saved, the student is notified too.",
    replyKeepOpen: "Reply and keep open",
    resolved: "Resolved",
    dismissReport: "Dismiss report",
    recoveryRequest: "Recovery request",
    plan: "Plan",
    closeHandling: "Close handling",
    handle: "Handle",
    recoveryMessagePlaceholder: "Message for the student after approving recovery…",
    resolveAndNotify: "Resolve and notify",
    rejectRequest: "Reject request",
    rejectionHint:
      "Rejecting does not create a separate student notification in API v1; resolving with a message does.",
    followUpItem: "Follow-up item",
    time: "Time",
    until: "to",
    reviewInterval: "Review interval",
    days: "days",
  },
};
