import type { AdminLanguage } from "../../../shared/ui/locale";

export const notificationCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    center: "اعلان‌های مدیر",
    centerDescription: "پیام‌ها، آزمون‌ها و اطلاعیه‌های بارگذاری‌شده را در همین‌جا پیگیری کنید.",
    inbox: "صندوق پیگیری",
    inboxDescription: "مشکلات و ریکاوری‌ها از همین صفحه قابل پاسخ و بستن هستند.",
    loadFailed: "دریافت اعلان‌ها ناموفق بود.",
    inboxFailed: "صندوق پیگیری دریافت نشد.",
    allRead: "همه اعلان‌ها خوانده شده‌اند.",
    noMatch: "اعلانی مطابق فیلتر پیدا نشد.",
    none: "اعلانی وجود ندارد.",
    noItems: "مورد فعالی برای این دانش‌آموز وجود ندارد.",
    markAll: "خواندن همه",
    refresh: "تازه‌سازی اعلان‌ها",
    search: "جستجوی اعلان‌ها",
    searchPlaceholder: "جستجو در اعلان‌های بارگذاری‌شده",
    type: "نوع اعلان",
    allTypes: "همه نوع‌ها",
    message: "پیام",
    exam: "آزمون",
    lesson: "برنامه",
    announcement: "اطلاعیه",
    readState: "وضعیت خواندن اعلان‌ها",
    all: "همه",
    unread: "خوانده‌نشده",
    more: "نمایش اعلان‌های بیشتر",
    unreadDot: "خوانده‌نشده",
    operational: "عملیاتی",
  },
  en: {
    center: "Admin notifications",
    centerDescription: "Follow loaded messages, exams, and announcements here.",
    inbox: "Follow-up inbox",
    inboxDescription: "Respond to and resolve issues and recovery requests from this workspace.",
    loadFailed: "Couldn’t load notifications.",
    inboxFailed: "Couldn’t load the follow-up inbox.",
    allRead: "All notifications are read.",
    noMatch: "No notification matches these filters.",
    none: "There are no notifications.",
    noItems: "There are no active items for this student.",
    markAll: "Mark all read",
    refresh: "Refresh notifications",
    search: "Search notifications",
    searchPlaceholder: "Search loaded notifications",
    type: "Notification type",
    allTypes: "All types",
    message: "Message",
    exam: "Exam",
    lesson: "Plan",
    announcement: "Announcement",
    readState: "Read status",
    all: "All",
    unread: "Unread",
    more: "Show more notifications",
    unreadDot: "Unread",
    operational: "actionable",
  },
};
