import type { AdminLanguage } from "../../../shared/ui/locale";

export const liveCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    searchStudents: "جستجوی دانش‌آموز",
    searchPlaceholder: "نام، پایه، رشته یا صفحه فعلی…",
    result: "نمایش",
    statusFilter: "فیلتر وضعیت",
    allStatuses: "همه وضعیت‌ها",
    online: "آنلاین",
    studying: "در حال مطالعه",
    paused: "متوقف",
    takingExam: "در حال آزمون",
    attention: "نیازمند توجه",
    offline: "آفلاین",
    livePanel: "پنل زنده",
    list: "فهرست",
    details: "جزئیات",
    events: "رویدادها",
    realtime: "عملیات بلادرنگ",
    lastSync: "آخرین همگام‌سازی:",
    waitingSync: "در انتظار اولین همگام‌سازی",
    loading: "در حال دریافت",
    refresh: "تازه‌سازی",
    all: "همه",
    noStudent: "یک دانش‌آموز را انتخاب کنید.",
    noMatches: "دانش‌آموزی با این جستجو یا فیلتر پیدا نشد.",
    noEvents: "هنوز رویدادی ثبت نشده است.",
    noAcademic: "بدون مشخصات تحصیلی",
    inApp: "داخل برنامه",
    noCurrentActivity: "بدون فعالیت جاری",
    noPresence: "بدون سابقه حضور",
    remainingTasks: "کار عقب‌افتاده",
    openRequest: "درخواست باز",
    openIssue: "مسئله باز",
    loadFailed: "دریافت وضعیت زنده ممکن نشد.",
    loadFailedHint: "اتصال را بررسی کنید و دوباره تلاش کنید.",
    retry: "تلاش دوباره",
    quickControls: "کنترل سریع",
    selectedDetails: "جزئیات فقط برای مورد انتخاب‌شده",
    operationsQueue: "صف عملیات دانش‌آموزان",
    recentEvents: "رویدادهای اخیر",
    currentActivity: "فعالیت فعلی",
    lastPresence: "آخرین حضور",
    requiresFollowUp: "این دانش‌آموز نیازمند پیگیری است.",
    priorityFollowUp: "پیگیری این دانش‌آموز در اولویت است.",
    profile: "پرونده",
    message: "پیام",
    noActivityRecorded: "فعالیتی ثبت نشده است.",
    activity: "فعالیت",
  },
  en: {
    searchStudents: "Search students",
    searchPlaceholder: "Name, grade, major, or current page…",
    result: "Showing",
    statusFilter: "Status filter",
    allStatuses: "All statuses",
    online: "Online",
    studying: "Studying",
    paused: "Paused",
    takingExam: "Taking an exam",
    attention: "Needs attention",
    offline: "Offline",
    livePanel: "Live panel",
    list: "List",
    details: "Details",
    events: "Events",
    realtime: "Live operations",
    lastSync: "Last synced:",
    waitingSync: "Waiting for the first sync",
    loading: "Loading",
    refresh: "Refresh",
    all: "All",
    noStudent: "Select a student.",
    noMatches: "No student matches this search or filter.",
    noEvents: "No events have been recorded yet.",
    noAcademic: "No academic details",
    inApp: "In the app",
    noCurrentActivity: "No current activity",
    noPresence: "No presence history",
    remainingTasks: "Overdue work",
    openRequest: "Open requests",
    openIssue: "Open issues",
    loadFailed: "Couldn’t load live status.",
    loadFailedHint: "Check the connection and try again.",
    retry: "Try again",
    quickControls: "Quick controls",
    selectedDetails: "Details for the selected record only",
    operationsQueue: "Student operations queue",
    recentEvents: "Recent events",
    currentActivity: "Current activity",
    lastPresence: "Last active",
    requiresFollowUp: "This student needs follow-up.",
    priorityFollowUp: "Follow-up for this student is a priority.",
    profile: "Profile",
    message: "Message",
    noActivityRecorded: "No activity has been recorded.",
    activity: "Activity",
  },
};

export const liveStateCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    online: "آنلاین",
    offline: "آفلاین",
    studying: "مطالعه",
    paused: "توقف",
    taking_exam: "آزمون",
  },
  en: {
    online: "Online",
    offline: "Offline",
    studying: "Studying",
    paused: "Paused",
    taking_exam: "Exam",
  },
};

export const liveActivityCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    "study.started": "شروع مطالعه",
    "study.paused": "توقف مطالعه",
    "study.resumed": "ادامه مطالعه",
    "study.finished": "پایان مطالعه",
    "task.done": "فعالیت انجام شد",
    "task.partial": "فعالیت نیمه‌کاره",
    "exam.started": "شروع آزمون",
    "exam.submitted": "ثبت آزمون",
    "screen.viewed": "مشاهده صفحه",
    empty: "جزئیات بیشتری ثبت نشده است.",
  },
  en: {
    "study.started": "Study started",
    "study.paused": "Study paused",
    "study.resumed": "Study resumed",
    "study.finished": "Study finished",
    "task.done": "Task completed",
    "task.partial": "Task partially completed",
    "exam.started": "Exam started",
    "exam.submitted": "Exam submitted",
    "screen.viewed": "Page viewed",
    empty: "No additional details were recorded.",
  },
};
