import type { AdminLanguage } from "../../../shared/ui/locale";

const copy = {
  fa: {
    eyebrow: "افراد و دسترسی",
    title: "گزارش‌های دانش‌آموزان",
    description: "دانش‌آموز، بازه زمانی و گزارش را در یک جریان انتخاب و بررسی کنید.",
    student: "دانش‌آموز",
    from: "از تاریخ",
    to: "تا تاریخ",
    quickRange: "بازه سریع:",
    days: (days: number) => `${days.toLocaleString("fa-IR")} روز`,
    selectStudent: "برای دیدن گزارش‌ها ابتدا یک دانش‌آموز را انتخاب کنید.",
    loading: "در حال دریافت گزارش‌ها",
    loadFailed: "دریافت گزارش‌ها انجام نشد.",
    loadFailedDescription: "اتصال یا پاسخ سرور را بررسی کنید و دوباره تلاش کنید.",
    retry: "تلاش دوباره",
    search: "جستجو در مسئله یا برنامه فردا",
    results: (visible: number, total: number) =>
      `${visible.toLocaleString("fa-IR")} گزارش از ${total.toLocaleString("fa-IR")} مورد`,
    order: "ترتیب گزارش‌ها",
    newest: "جدیدترین",
    oldest: "قدیمی‌ترین",
    view: "نوع نمایش",
    cards: "نمای کارت",
    compact: "نمای فشرده",
    noMatches: "گزارشی مطابق جستجوی شما پیدا نشد.",
    noRange: (from: string, to: string) => `برای بازه انتخابی گزارشی نیست. ${from} تا ${to}`,
    daily: "گزارش روزانه",
    noDate: "بدون تاریخ",
    focus: "تمرکز",
    motivation: "انگیزه",
    fatigue: "خستگی",
    study: "مطالعه",
    hours: "ساعت",
    tests: "تست",
    correct: "صحیح",
    incorrect: "غلط",
    accuracy: "دقت",
    problem: "مسئله",
    tomorrow: "فردا",
    note: "یادداشت",
    summary: "خلاصه بازه انتخابی",
    reportCount: "تعداد گزارش",
    studyHours: "ساعت مطالعه",
    testCount: "تعداد تست",
    averageFocus: "میانگین تمرکز",
    averageMotivation: "میانگین انگیزه",
    averageFatigue: "میانگین خستگی",
  },
  en: {
    eyebrow: "People and access",
    title: "Student reports",
    description: "Select a student and time range, then review their reports in one flow.",
    student: "Student",
    from: "From date",
    to: "To date",
    quickRange: "Quick range:",
    days: (days: number) => `${days.toLocaleString("en-US")} days`,
    selectStudent: "Select a student first to view reports.",
    loading: "Loading reports",
    loadFailed: "Could not load reports.",
    loadFailedDescription: "Check the connection or server response, then try again.",
    retry: "Try again",
    search: "Search problem or tomorrow’s plan",
    results: (visible: number, total: number) =>
      `${visible.toLocaleString("en-US")} reports of ${total.toLocaleString("en-US")}`,
    order: "Report order",
    newest: "Newest first",
    oldest: "Oldest first",
    view: "Display mode",
    cards: "Card view",
    compact: "Compact view",
    noMatches: "No reports match your search.",
    noRange: (from: string, to: string) =>
      `There are no reports for the selected range: ${from} to ${to}.`,
    daily: "Daily report",
    noDate: "No date",
    focus: "Focus",
    motivation: "Motivation",
    fatigue: "Fatigue",
    study: "Study",
    hours: "hours",
    tests: "Tests",
    correct: "Correct",
    incorrect: "Incorrect",
    accuracy: "Accuracy",
    problem: "Problem",
    tomorrow: "Tomorrow",
    note: "Note",
    summary: "Selected-range summary",
    reportCount: "Reports",
    studyHours: "Study hours",
    testCount: "Tests",
    averageFocus: "Average focus",
    averageMotivation: "Average motivation",
    averageFatigue: "Average fatigue",
  },
} as const;

export function reportCopy(language: AdminLanguage) {
  return copy[language];
}
