import type { AdminLanguage } from "../../../shared/ui/locale";

export const dashboardCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    attentionTitle: "دانش‌آموزان نیازمند توجه",
    attentionDescription: "بر اساس مرورهای عقب‌افتاده، عملکرد آزمون و آخرین فعالیت واقعی.",
    attentionFilter: "فیلتر شدت توجه",
    all: "همه",
    critical: "بحرانی",
    warning: "هشدار",
    loadFailed: "فهرست توجه دریافت نشد.",
    retry: "تلاش دوباره",
    academicProfile: "پروفایل آموزشی",
    online: "آنلاین",
    noActivity: "بدون فعالیت ثبت‌شده",
    remainingTasks: "فعالیت باقی‌مانده",
    followUp: "پیگیری",
    openProfile: "بازکردن پروفایل",
    profileTitle: "پروفایل دانش‌آموز",
    noAttention: "دانش‌آموزی با هشدار فعال وجود ندارد.",
    noSeverity: "موردی در این سطح هشدار وجود ندارد.",
    dashboardLoading: "در حال دریافت نمای کلی مدیریت…",
    dashboardFailed: "اطلاعات داشبورد مدیریت دریافت نشد.",
    refresh: "بروزرسانی",
    activeStudents: "دانش‌آموز فعال",
    activeAccounts: "حساب‌های فعال سامانه",
    todayPlans: "برنامه امروز",
    readyPlans: "برنامه آماده اجرا",
    todayReports: "گزارش امروز",
    submittedReports: "گزارش ثبت شده",
    upcomingExams: "آزمون پیش‌رو",
    futureExams: "آزمون‌های آینده",
    active: "فعال",
    today: "امروز",
    received: "دریافت شده",
    pending: "در انتظار",
    nextStep: "گام بعدی شما",
    nextStepDescription: "ابزارهای مجاز برای نقش فعال؛ هر مورد شما را به محل انجام کار می‌برد.",
    todayFollowUp: "صف پیگیری امروز",
    followUpDescription: "موارد عملیاتی که نیاز به بررسی یا پاسخ دارند.",
    recentReports: "آخرین گزارش‌های روزانه",
    reportsDescription: "داده واقعی API؛ بدون فعالیت یا عدد نمونه در داشبورد.",
    allReports: "همه گزارش‌ها",
    noReports: "هنوز گزارش روزانه‌ای ثبت نشده است.",
    study: "مطالعه",
    hours: "ساعت",
    tests: "تست",
    accuracy: "دقت",
    view: "مشاهده",
    student: "دانش‌آموز",
    workspaceLoading: "در حال آماده‌سازی میز کار نقش فعال…",
    workspaceUnavailable: "داشبورد این نقش دریافت نشد.",
    refreshWorkspace: "به‌روزرسانی داده‌های داشبورد",
    defaultWorkspaceTitle: "داشبورد",
    defaultWorkspaceDescription: "نمای کلی فضای کاری شما",
    guardianWorkspaceTitle: "نمای خانواده",
    guardianWorkspaceDescription: "برنامه، پیشرفت و ارتباط با تیم آموزشی فرزندتان",
    advisorWorkspaceTitle: "میز کار مشاور",
    advisorWorkspaceDescription: "پیگیری برنامه‌ها، درخواست‌ها و دانش‌آموزان نیازمند توجه",
    teacherWorkspaceTitle: "میز کار دبیر",
    teacherWorkspaceDescription: "کلاس‌ها، آزمون‌ها و الگوهای خطای دانش‌آموزان",
    mentorWorkspaceTitle: "میز کار منتور",
    mentorWorkspaceDescription: "هدف‌ها، روند روزانه و گفت‌وگوهای دانش‌آموزان",
    contentManagerWorkspaceTitle: "استودیوی محتوای آموزشی",
    contentManagerWorkspaceDescription: "درس‌ها، سؤال‌ها، آزمون‌ها و آزمونک‌های در حال انتشار",
    organizationAdminWorkspaceTitle: "مدیریت سازمان",
    organizationAdminWorkspaceDescription: "اعضا، کارکنان، دانش‌آموزان و سلامت عملیاتی سازمان",
    platformAdminWorkspaceTitle: "فرماندهی پلتفرم",
    platformAdminWorkspaceDescription: "سازمان‌ها، کاربران، امنیت و نسخه‌های در حال اجرا",
    assignedStudents: "دانش‌آموز تحت پوشش",
    assignedStudentsHint: "در محدوده نقش فعال",
    unreadMessages: "پیام خوانده‌نشده",
    unreadMessagesHint: "گفت‌وگوهای نیازمند پاسخ",
    children: "فرزندان",
    childrenHint: "پروفایل‌های متصل و تأییدشده",
    needsAttention: "نیازمند توجه",
    needsAttentionHint: "دانش‌آموز با پیگیری باز",
    recoveryRequests: "درخواست بازیابی",
    recoveryRequestsHint: "در انتظار تصمیم",
    taskIssues: "مسئله فعالیت",
    taskIssuesHint: "گزارش باز دانش‌آموز",
    retryRequests: "تلاش مجدد",
    retryRequestsHint: "درخواست آزمون",
    activeSubjects: "درس فعال",
    activeSubjectsHint: "درس‌های تخصیص‌یافته",
    openIssues: "خطای باز",
    openIssuesHint: "نیازمند مرور آموزشی",
    questionBank: "بانک سؤال",
    questionBankHint: "سؤال‌های آماده",
    todayPlansMetric: "برنامه امروز",
    todayPlansHint: "برنامه‌های تحت پیگیری",
    upcomingGoalsMetric: "هدف پیش‌رو",
    upcomingGoalsHint: "آزمون و هدف آینده",
    subjectsMetric: "درس",
    subjectsHint: "درس‌های فعال",
    questionsMetric: "سؤال",
    questionsHint: "بانک محتوای آزمون",
    quizzesMetric: "آزمونک",
    quizzesHint: "پیش‌نویس",
    examsMetric: "آزمون",
    examsHint: "محتوای ارزیابی",
    activeMembers: "اعضای فعال",
    activeMembersHint: "عضویت معتبر سازمان",
    studentsMetric: "دانش‌آموز",
    studentsHint: "حساب آموزشی",
    staffMetric: "کارکنان",
    staffHint: "تیم سازمان",
    inactiveUsers: "کاربر غیرفعال",
    inactiveUsersHint: "نیازمند بررسی حساب",
    organizationsMetric: "سازمان",
    organizationsHint: "محدوده‌های پلتفرم",
    usersMetric: "کاربر",
    usersHint: "تمام حساب‌های سامانه",
    securityEvents: "رویداد امنیتی",
    securityEventsHint: "در ۲۴ ساعت گذشته",
    lockedLogins: "ورود قفل‌شده",
    lockedLoginsHint: "محدودیت فعال ورود",
  },
  en: {
    attentionTitle: "Students needing attention",
    attentionDescription:
      "Based on overdue reviews, exam performance, and the most recent real activity.",
    attentionFilter: "Attention severity filter",
    all: "All",
    critical: "Critical",
    warning: "Warning",
    loadFailed: "Couldn’t load the attention list.",
    retry: "Try again",
    academicProfile: "Academic profile",
    online: "Online",
    noActivity: "No recorded activity",
    remainingTasks: "remaining tasks",
    followUp: "Follow up",
    openProfile: "Open profile",
    profileTitle: "Student profile",
    noAttention: "There are no students with an active alert.",
    noSeverity: "There are no items at this severity.",
    dashboardLoading: "Loading the administration overview…",
    dashboardFailed: "Couldn’t load the administration dashboard.",
    refresh: "Refresh",
    activeStudents: "Active students",
    activeAccounts: "Active platform accounts",
    todayPlans: "Today’s plans",
    readyPlans: "Plans ready to run",
    todayReports: "Today’s reports",
    submittedReports: "Submitted reports",
    upcomingExams: "Upcoming exams",
    futureExams: "Future exams",
    active: "Active",
    today: "Today",
    received: "Received",
    pending: "Pending",
    nextStep: "Your next step",
    nextStepDescription:
      "Tools available to your active role; each takes you to the place to do the work.",
    todayFollowUp: "Today’s follow-up queue",
    followUpDescription: "Operational items that need review or a response.",
    recentReports: "Latest daily reports",
    reportsDescription: "Live API data only; no sample activity or numbers on the dashboard.",
    allReports: "All reports",
    noReports: "No daily reports have been submitted yet.",
    study: "Study",
    hours: "hours",
    tests: "tests",
    accuracy: "Accuracy",
    view: "View",
    student: "Student",
    workspaceLoading: "Preparing the active role workspace…",
    workspaceUnavailable: "This role dashboard could not be loaded.",
    refreshWorkspace: "Refresh dashboard data",
    defaultWorkspaceTitle: "Dashboard",
    defaultWorkspaceDescription: "An overview of your workspace.",
    guardianWorkspaceTitle: "Family view",
    guardianWorkspaceDescription:
      "Your child’s plan, progress, and contact with the education team.",
    advisorWorkspaceTitle: "Advisor workspace",
    advisorWorkspaceDescription: "Follow up plans, requests, and students who need attention.",
    teacherWorkspaceTitle: "Teacher workspace",
    teacherWorkspaceDescription: "Classes, assessments, and student error patterns.",
    mentorWorkspaceTitle: "Mentor workspace",
    mentorWorkspaceDescription: "Goals, daily progress, and student conversations.",
    contentManagerWorkspaceTitle: "Learning content studio",
    contentManagerWorkspaceDescription: "Subjects, questions, exams, and quizzes being published.",
    organizationAdminWorkspaceTitle: "Organization management",
    organizationAdminWorkspaceDescription: "Members, staff, students, and operational health.",
    platformAdminWorkspaceTitle: "Platform command",
    platformAdminWorkspaceDescription: "Organizations, users, security, and running versions.",
    assignedStudents: "Assigned students",
    assignedStudentsHint: "Within the active role’s scope",
    unreadMessages: "Unread messages",
    unreadMessagesHint: "Conversations needing a response",
    children: "Children",
    childrenHint: "Linked and confirmed profiles",
    needsAttention: "Needs attention",
    needsAttentionHint: "Students with an open follow-up",
    recoveryRequests: "Recovery requests",
    recoveryRequestsHint: "Awaiting a decision",
    taskIssues: "Task issues",
    taskIssuesHint: "Open student reports",
    retryRequests: "Retry requests",
    retryRequestsHint: "Assessment requests",
    activeSubjects: "Active subjects",
    activeSubjectsHint: "Assigned subjects",
    openIssues: "Open issues",
    openIssuesHint: "Need academic review",
    questionBank: "Question bank",
    questionBankHint: "Questions ready to use",
    todayPlansMetric: "Today’s plans",
    todayPlansHint: "Plans being followed up",
    upcomingGoalsMetric: "Upcoming goals",
    upcomingGoalsHint: "Future assessments and goals",
    subjectsMetric: "Subjects",
    subjectsHint: "Active subjects",
    questionsMetric: "Questions",
    questionsHint: "Assessment content bank",
    quizzesMetric: "Quizzes",
    quizzesHint: "Drafts",
    examsMetric: "Exams",
    examsHint: "Assessment content",
    activeMembers: "Active members",
    activeMembersHint: "Valid organization memberships",
    studentsMetric: "Students",
    studentsHint: "Learning accounts",
    staffMetric: "Staff",
    staffHint: "Organization team",
    inactiveUsers: "Inactive users",
    inactiveUsersHint: "Accounts needing review",
    organizationsMetric: "Organizations",
    organizationsHint: "Platform scopes",
    usersMetric: "Users",
    usersHint: "All system accounts",
    securityEvents: "Security events",
    securityEventsHint: "In the past 24 hours",
    lockedLogins: "Locked sign-ins",
    lockedLoginsHint: "Active sign-in restrictions",
  },
};
