import type { AdminLanguage } from "../../../shared/ui/locale";

export const dashboardCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    attentionTitle: "دانش‌آموزان نیازمند توجه",
    attentionDescription: "بر اساس مرورهای عقب‌افتاده، عملکرد آزمون و آخرین فعالیت واقعی.",
    attentionFilter: "فیلتر شدت توجه",
    all: "همه",
    critical: "بحرانی",
    warning: "هشدار",
    loadFailed: "فهرست توجه دریافت نشد.",
    retry: "تلاش دوباره",
    academicProfile: "پروفایل آموزشی",
    online: "آنلاین",
    noActivity: "بدون فعالیت ثبت‌شده",
    remainingTasks: "فعالیت باقی‌مانده",
    followUp: "پیگیری",
    openProfile: "بازکردن پروفایل",
    profileTitle: "پروفایل دانش‌آموز",
    noAttention: "دانش‌آموزی با هشدار فعال وجود ندارد.",
    noSeverity: "موردی در این سطح هشدار وجود ندارد.",
    dashboardLoading: "در حال دریافت نمای کلی مدیریت…",
    dashboardFailed: "اطلاعات داشبورد مدیریت دریافت نشد.",
    refresh: "بروزرسانی",
    activeStudents: "دانش‌آموز فعال",
    activeAccounts: "حساب‌های فعال سامانه",
    todayPlans: "برنامه امروز",
    readyPlans: "برنامه آماده اجرا",
    todayReports: "گزارش امروز",
    submittedReports: "گزارش ثبت شده",
    upcomingExams: "آزمون پیش‌رو",
    futureExams: "آزمون‌های آینده",
    active: "فعال",
    today: "امروز",
    received: "دریافت شده",
    pending: "در انتظار",
    nextStep: "گام بعدی شما",
    nextStepDescription: "ابزارهای مجاز برای نقش فعال؛ هر مورد شما را به محل انجام کار می‌برد.",
    todayFollowUp: "صف پیگیری امروز",
    followUpDescription: "موارد عملیاتی که نیاز به بررسی یا پاسخ دارند.",
    recentReports: "آخرین گزارش‌های روزانه",
    reportsDescription: "داده واقعی API؛ بدون فعالیت یا عدد نمونه در داشبورد.",
    allReports: "همه گزارش‌ها",
    noReports: "هنوز گزارش روزانه‌ای ثبت نشده است.",
    study: "مطالعه",
    hours: "ساعت",
    tests: "تست",
    accuracy: "دقت",
    view: "مشاهده",
    student: "دانش‌آموز",
  },
  en: {
    attentionTitle: "Students needing attention",
    attentionDescription:
      "Based on overdue reviews, exam performance, and the most recent real activity.",
    attentionFilter: "Attention severity filter",
    all: "All",
    critical: "Critical",
    warning: "Warning",
    loadFailed: "Couldn’t load the attention list.",
    retry: "Try again",
    academicProfile: "Academic profile",
    online: "Online",
    noActivity: "No recorded activity",
    remainingTasks: "remaining tasks",
    followUp: "Follow up",
    openProfile: "Open profile",
    profileTitle: "Student profile",
    noAttention: "There are no students with an active alert.",
    noSeverity: "There are no items at this severity.",
    dashboardLoading: "Loading the administration overview…",
    dashboardFailed: "Couldn’t load the administration dashboard.",
    refresh: "Refresh",
    activeStudents: "Active students",
    activeAccounts: "Active platform accounts",
    todayPlans: "Today’s plans",
    readyPlans: "Plans ready to run",
    todayReports: "Today’s reports",
    submittedReports: "Submitted reports",
    upcomingExams: "Upcoming exams",
    futureExams: "Future exams",
    active: "Active",
    today: "Today",
    received: "Received",
    pending: "Pending",
    nextStep: "Your next step",
    nextStepDescription:
      "Tools available to your active role; each takes you to the place to do the work.",
    todayFollowUp: "Today’s follow-up queue",
    followUpDescription: "Operational items that need review or a response.",
    recentReports: "Latest daily reports",
    reportsDescription: "Live API data only; no sample activity or numbers on the dashboard.",
    allReports: "All reports",
    noReports: "No daily reports have been submitted yet.",
    study: "Study",
    hours: "hours",
    tests: "tests",
    accuracy: "Accuracy",
    view: "View",
    student: "Student",
  },
};
