import type { AdminLanguage } from "../../../shared/ui/locale";

export const chatCopy: Record<AdminLanguage, Record<string, string>> = {
  fa: {
    conversations: "گفتگوها",
    description: "جستجو، فیلتر و ادامه گفتگوهای کاری در یک فهرست یکپارچه.",
    loadFailed: "دریافت گفتگوها ناموفق بود.",
    noMatch: "گفتگویی مطابق جستجو و فیلتر نیست.",
    none: "گفتگویی وجود ندارد.",
    unread: "خوانده‌نشده",
    loading: "در حال تازه‌سازی",
    more: "گفتگوهای بیشتر",
    search: "جستجوی گفتگوها",
    placeholder: "نام، پایه یا متن آخرین پیام",
    clear: "پاک",
    filters: "فیلتر گفتگوها",
    all: "همه",
    favorites: "مهم",
    drafts: "پیش‌نویس",
    students: "دانش‌آموزان",
    groups: "گروه‌ها",
    sort: "مرتب‌سازی",
    recent: "آخرین فعالیت",
    unreadFirst: "خوانده‌نشده اول",
    onlineFirst: "آنلاین اول",
    name: "نام",
    messages: "پیام‌های گفتگو",
    older: "پیام‌های قدیمی‌تر",
    loadingHistory: "در حال دریافت تاریخچه",
    beginning: "ابتدای گفتگو",
    messagesFailed: "دریافت پیام‌ها ناموفق بود.",
    deleteMessage: "حذف پیام؟",
    deleteDescription: "متن پیام برای اعضای گفتگو حذف خواهد شد.",
    delete: "حذف پیام",
    noMessages: "هنوز پیامی ثبت نشده است.",
    startMessage: "برای شروع گفتگو، پیام خود را در کادر پایین بنویسید.",
    newMessages: "پیام جدید",
    goLatest: "رفتن به آخر گفتگو",
    selectConversation: "یک گفتگو را انتخاب کنید.",
    selectDescription: "از فهرست گفتگوها یک دانش‌آموز یا گروه را باز کنید؛ یا گفتگوی جدید بسازید.",
    tryAgain: "تلاش دوباره",
    sendFailed: "ارسال پیام ناموفق بود.",
    unavailableMessage: "این پیام هنوز در تاریخچه بارگذاری‌شده نیست.",
    openConversation: "باز کردن گفتگوی {name}",
    draftPrefix: "پیش‌نویس: {text}",
    structuredMessage: "پیام ساختاریافته",
    noMessagesShort: "هنوز پیامی ثبت نشده",
    group: "گروه",
    conversation: "گفتگو",
    viewStudentProfile: "نمایش پروفایل دانش‌آموز",
    removeFavorite: "حذف از مهم‌ها",
    addFavorite: "افزودن به مهم‌ها",
    noOrganization: "بدون سازمان",
    noAdvisor: "بدون مشاور",
    advisorPrefix: "مشاور: {name}",
    backToConversations: "بازگشت به گفتگوها",
    viewConversationProfile: "مشاهده پروفایل گفتگو",
    groupImage: "تصویر گروه",
    online: "آنلاین",
    offline: "آفلاین",
    membersRole: "{count} عضو • {role}",
    loadingRole: "در حال دریافت نقش",
    owner: "مالک",
    admin: "مدیر",
    member: "عضو",
    searchMessages: "جستجو در پیام‌ها",
    searchMessagesShortcut: "جستجو در پیام‌ها (Ctrl/Cmd+F)",
    markedRead: "خوانده شد",
    conversationProfile: "پروفایل گفتگو",
    closeProfile: "بستن پروفایل",
    noProfileBio: "اطلاعات بیشتری ثبت نشده است.",
    allowUsername: "اجازه تغییر نام کاربری",
    usernameAllowed: "امکان تغییر نام کاربری فعال شد.",
    usernameFailed: "فعال‌سازی ناموفق بود.",
    profileFailed: "دریافت پروفایل ناموفق بود.",
    searchLoadedMessages: "جستجو در پیام‌های بارگذاری‌شده…",
    previousResult: "نتیجه قبلی",
    nextResult: "نتیجه بعدی",
    closeSearch: "بستن جستجو",
    reply: "پاسخ",
    copyMessage: "کپی",
    edit: "ویرایش",
    reaction: "واکنش {emoji}",
    loadingReactions: "در حال دریافت واکنش‌ها",
    groupMember: "عضو گروه",
    previousMessage: "پیام قبلی",
    sending: "در حال ارسال",
    edited: "ویرایش‌شده",
    deletedMessage: "پیام حذف شده است.",
    noTextMessage: "پیام بدون متن",
    replyTo: "پاسخ به {name}: {text}",
    cancelReply: "لغو پاسخ",
    editPreview: "ویرایش: {text}",
    cancelEdit: "لغو ویرایش",
    messageUnavailable: "ارسال پیام امکان‌پذیر نیست",
    messagePlaceholder: "پیام...",
    messageText: "متن پیام",
    newLineShortcut: "Shift+Enter خط جدید",
    addEmoji: "افزودن شکلک",
    sendMessage: "ارسال پیام",
    sendingMessage: "در حال ارسال پیام",
    quickReplies: "پاسخ‌های سریع",
    manageQuickReplies: "مدیریت پاسخ‌های سریع",
    newQuickReplyPlaceholder: "پاسخ جدید؛ {name} با نام مخاطب جایگزین می‌شود",
    addQuickReply: "افزودن پاسخ سریع",
    removeQuickReply: "حذف پاسخ سریع",
    newDirect: "گفتگوی مستقیم تازه",
    newDirectDescription: "کاربر مجاز را پیدا کنید و گفتگو را باز کنید.",
    newConversation: "گفتگوی جدید",
    userNameOrUsername: "نام یا نام کاربری",
    conversationReady: "گفتگو آماده شد.",
    createConversationFailed: "ساخت گفتگو انجام نشد.",
    searching: "در حال جستجو…",
    noUserFound: "کاربری پیدا نشد.",
    createGroup: "ساخت گروه",
    createGroupDescription: "یک گفتگوی گروهی جدید بسازید و اعضای موردنظر را اضافه کنید.",
    groupCreated: "گفتگوی گروهی با موفقیت ساخته شد.",
    groupReady: "گروه جدید آماده استفاده است.",
    createGroupFailed: "ساخت گفتگوی گروهی انجام نشد.",
    unknownError: "خطای ناشناخته رخ داد.",
    groupName: "نام گروه",
    groupDescription: "توضیحات",
    addInitialMembers: "افزودن اعضای اولیه",
    cancel: "انصراف",
    groupInfo: "اطلاعات و مدیریت گروه",
    groupChangesSaved: "تغییرات گروه ذخیره شد.",
    groupActionFailed: "عملیات گروه ناموفق بود.",
    groupInfoFailed: "دریافت اطلاعات گروه ناموفق بود.",
    members: "اعضا",
    searchMembers: "جستجو میان اعضا",
    searchGroupMembers: "جستجو میان اعضای گروه",
    noMatchingMembers: "عضوی با این جستجو پیدا نشد.",
    searchForMoreMembers: "برای دسترسی به اعضای بیشتر، نام یا نام کاربری را جستجو کنید.",
    addMember: "افزودن عضو",
    enableNotifications: "فعال‌کردن اعلان",
    muteGroup: "بی‌صدا کردن",
    archiveGroup: "بایگانی گروه",
    archiveGroupConfirm: "بایگانی گروه؟",
    archiveGroupDescription: "گروه از فهرست گفتگوهای فعال همه اعضا خارج می‌شود.",
    archive: "بایگانی",
    leaveGroup: "ترک گروه",
    leaveGroupConfirm: "ترک گروه؟",
    leaveGroupDescription: "برای دسترسی دوباره باید یکی از مدیران شما را به گروه اضافه کند.",
    groupDetails: "مشخصات گروه",
    saveDetails: "ذخیره مشخصات",
    noDescription: "بدون توضیحات",
    becomeMember: "عضو شود",
    becomeAdmin: "مدیر شود",
    transferOwnership: "انتقال مالکیت به {name}",
    transferOwnershipConfirm: "انتقال مالکیت گروه؟",
    transferOwnershipDescription: "{name} مالک جدید می‌شود و نقش شما به مدیر تغییر می‌کند.",
    transferOwnershipAction: "انتقال مالکیت",
    removeMemberFromGroup: "حذف {name} از گروه",
    removeMemberConfirm: "حذف عضو از گروه؟",
    removeMemberDescription: "{name} دسترسی خود به این گفتگو را از دست می‌دهد.",
    permissions: "دسترسی‌های اعضا",
    savePermissions: "ذخیره دسترسی‌ها",
    permissionSend: "اعضا بتوانند پیام بفرستند",
    permissionAddMembers: "اعضا بتوانند عضو اضافه کنند",
    permissionInvite: "اعضا بتوانند دعوت کنند",
    permissionReact: "اعضا بتوانند واکنش بگذارند",
    permissionMentions: "اعضا بتوانند منشن کنند",
    permissionStudyState: "اشتراک وضعیت مطالعه",
    permissionExamResults: "اشتراک نتیجه آزمون",
    permissionLearningProgress: "اشتراک پیشرفت یادگیری",
    permissionEditOwn: "ویرایش پیام توسط فرستنده",
    permissionDeleteOwn: "حذف پیام توسط فرستنده",
    permissionAdminsDelete: "مدیران بتوانند پیام‌ها را حذف کنند",
  },
  en: {
    conversations: "Conversations",
    description: "Search, filter, and continue operational conversations from one unified list.",
    loadFailed: "Couldn’t load conversations.",
    noMatch: "No conversation matches this search and filter.",
    none: "There are no conversations.",
    unread: "unread",
    loading: "Refreshing",
    more: "More conversations",
    search: "Search conversations",
    placeholder: "Name, grade, or last message",
    clear: "Clear",
    filters: "Conversation filters",
    all: "All",
    favorites: "Favorites",
    drafts: "Drafts",
    students: "Students",
    groups: "Groups",
    sort: "Sort",
    recent: "Recent activity",
    unreadFirst: "Unread first",
    onlineFirst: "Online first",
    name: "Name",
    messages: "Conversation messages",
    older: "Older messages",
    loadingHistory: "Loading history",
    beginning: "Beginning of conversation",
    messagesFailed: "Couldn’t load messages.",
    deleteMessage: "Delete message?",
    deleteDescription: "The message text will be removed for conversation members.",
    delete: "Delete message",
    noMessages: "No messages yet.",
    startMessage: "Write a message below to start this conversation.",
    newMessages: "new messages",
    goLatest: "Go to latest message",
    selectConversation: "Select a conversation.",
    selectDescription: "Open a student or group from the list, or create a new conversation.",
    tryAgain: "Try again",
    sendFailed: "Couldn’t send the message.",
    unavailableMessage: "This message is not in the loaded history yet.",
    openConversation: "Open conversation with {name}",
    draftPrefix: "Draft: {text}",
    structuredMessage: "Structured message",
    noMessagesShort: "No messages yet",
    group: "Group",
    conversation: "Conversation",
    viewStudentProfile: "View student profile",
    removeFavorite: "Remove from favorites",
    addFavorite: "Add to favorites",
    noOrganization: "No organization",
    noAdvisor: "No advisor",
    advisorPrefix: "Advisor: {name}",
    backToConversations: "Back to conversations",
    viewConversationProfile: "View conversation profile",
    groupImage: "Group image",
    online: "Online",
    offline: "Offline",
    membersRole: "{count} members • {role}",
    loadingRole: "Loading role",
    owner: "Owner",
    admin: "Admin",
    member: "Member",
    searchMessages: "Search messages",
    searchMessagesShortcut: "Search messages (Ctrl/Cmd+F)",
    markedRead: "Marked read",
    conversationProfile: "Conversation profile",
    closeProfile: "Close profile",
    noProfileBio: "No additional profile information.",
    allowUsername: "Allow username change",
    usernameAllowed: "Username changes are now allowed.",
    usernameFailed: "Couldn’t allow username changes.",
    profileFailed: "Couldn’t load the profile.",
    searchLoadedMessages: "Search loaded messages…",
    previousResult: "Previous result",
    nextResult: "Next result",
    closeSearch: "Close search",
    reply: "Reply",
    copyMessage: "Copy",
    edit: "Edit",
    reaction: "React with {emoji}",
    loadingReactions: "Loading reactions",
    groupMember: "Group member",
    previousMessage: "Previous message",
    sending: "Sending",
    edited: "Edited",
    deletedMessage: "Message deleted.",
    noTextMessage: "Message has no text",
    replyTo: "Replying to {name}: {text}",
    cancelReply: "Cancel reply",
    editPreview: "Editing: {text}",
    cancelEdit: "Cancel editing",
    messageUnavailable: "Messaging is unavailable",
    messagePlaceholder: "Message…",
    messageText: "Message text",
    newLineShortcut: "Shift+Enter for a new line",
    addEmoji: "Add emoji",
    sendMessage: "Send message",
    sendingMessage: "Sending message",
    quickReplies: "Quick replies",
    manageQuickReplies: "Manage quick replies",
    newQuickReplyPlaceholder: "New reply; {name} will be replaced with the recipient name",
    addQuickReply: "Add quick reply",
    removeQuickReply: "Remove quick reply",
    newDirect: "New direct conversation",
    newDirectDescription: "Find an eligible user and open a conversation.",
    newConversation: "New conversation",
    userNameOrUsername: "Name or username",
    conversationReady: "Conversation is ready.",
    createConversationFailed: "Couldn’t create the conversation.",
    searching: "Searching…",
    noUserFound: "No user found.",
    createGroup: "Create group",
    createGroupDescription: "Create a new group conversation and add its first members.",
    groupCreated: "Group conversation created.",
    groupReady: "The new group is ready to use.",
    createGroupFailed: "Couldn’t create the group conversation.",
    unknownError: "An unknown error occurred.",
    groupName: "Group name",
    groupDescription: "Description",
    addInitialMembers: "Add initial members",
    cancel: "Cancel",
    groupInfo: "Group information and management",
    groupChangesSaved: "Group changes saved.",
    groupActionFailed: "The group action couldn’t be completed.",
    groupInfoFailed: "Couldn’t load group information.",
    members: "Members",
    searchMembers: "Search members",
    searchGroupMembers: "Search group members",
    noMatchingMembers: "No member matches this search.",
    searchForMoreMembers: "Search by name or username to access more members.",
    addMember: "Add member",
    enableNotifications: "Enable notifications",
    muteGroup: "Mute group",
    archiveGroup: "Archive group",
    archiveGroupConfirm: "Archive group?",
    archiveGroupDescription: "The group will leave every member’s active conversation list.",
    archive: "Archive",
    leaveGroup: "Leave group",
    leaveGroupConfirm: "Leave group?",
    leaveGroupDescription: "An administrator must add you again before you can access this group.",
    groupDetails: "Group details",
    saveDetails: "Save details",
    noDescription: "No description",
    becomeMember: "Make member",
    becomeAdmin: "Make admin",
    transferOwnership: "Transfer ownership to {name}",
    transferOwnershipConfirm: "Transfer group ownership?",
    transferOwnershipDescription:
      "{name} will become the owner and your role will change to admin.",
    transferOwnershipAction: "Transfer ownership",
    removeMemberFromGroup: "Remove {name} from group",
    removeMemberConfirm: "Remove member from group?",
    removeMemberDescription: "{name} will lose access to this conversation.",
    permissions: "Member permissions",
    savePermissions: "Save permissions",
    permissionSend: "Allow members to send messages",
    permissionAddMembers: "Allow members to add members",
    permissionInvite: "Allow members to invite others",
    permissionReact: "Allow members to react",
    permissionMentions: "Allow members to use mentions",
    permissionStudyState: "Share study state",
    permissionExamResults: "Share exam results",
    permissionLearningProgress: "Share learning progress",
    permissionEditOwn: "Allow senders to edit their messages",
    permissionDeleteOwn: "Allow senders to delete their messages",
    permissionAdminsDelete: "Allow admins to delete messages",
  },
};
