import { useLocale } from "../../shared/ui/locale";

const copy = {
  fa: {
    editTitle: "ویرایش سؤال بانک",
    newTitle: "سؤال جدید در بانک",
    editDescription: "ویرایش این منبع، نسخه‌های کپی‌شده در آزمون‌ها و آزمونک‌ها را تغییر نمی‌دهد.",
    loading: "در حال دریافت بانک سؤال…",
    failed: "دریافت بانک سؤال ناموفق بود.",
    bank: "بانک سؤال آزمون",
    description: "منبع‌های مستقل و قابل‌استفادهٔ مجدد برای ساخت آزمون",
    newQuestion: "سؤال جدید",
    buildExam: "ساخت آزمون",
    buildTitle: "ساخت آزمون از بانک سؤال",
    buildDescription: "ابتدا پیش‌نمایش را بررسی کنید؛ افزودن سؤال فقط با تأیید صریح انجام می‌شود.",
    search: "جست‌وجو در سؤال، درس، مبحث یا برچسب",
    noSubject: "بدون درس",
    edit: "ویرایش",
    archive: "بایگانی",
    archiveTitle: "بایگانی سؤال بانک؟",
    archiveDescription: "نسخه‌های اضافه‌شده به آزمون یا آزمونک بدون تغییر می‌مانند.",
    none: "سؤال منبعی با این جست‌وجو پیدا نشد.",
    organization: "سازمان را انتخاب کنید",
    question: "متن سؤال",
    correctOption: (n: number) => `پاسخ صحیح گزینه ${n}`,
    option: (n: number) => `گزینه ${n}`,
    subject: "درس",
    topic: "مبحث",
    grade: "پایه",
    chapter: "فصل",
    lesson: "درس‌نامه",
    tags: "برچسب‌ها، با ویرگول جدا کنید",
    explanation: "توضیح پاسخ (اختیاری)",
    save: "ذخیره سؤال",
    cancel: "انصراف",
    easy: "آسان",
    medium: "متوسط",
    hard: "سخت",
    selectExam: "آزمون هدف را انتخاب کنید",
    noMatches: "سؤال منطبق با ترکیب انتخاب‌شده پیدا نشد.",
    added: (count: number, skipped: number, locale: string) =>
      `${count.toLocaleString(locale)} سؤال به آزمون افزوده شد.${skipped ? ` ${skipped.toLocaleString(locale)} سؤال تکراری رد شد.` : ""}`,
    failedBuild: "ساخت آزمون از بانک ناموفق بود.",
    preview: (count: number, locale: string) => `پیش‌نمایش ${count.toLocaleString(locale)} سؤال`,
    confirmAdd: "تأیید و افزودن",
  },
  en: {
    editTitle: "Edit bank question",
    newTitle: "New bank question",
    editDescription:
      "Editing this source does not change copies already added to exams or quizzes.",
    loading: "Loading question bank…",
    failed: "Could not load the question bank.",
    bank: "Exam question bank",
    description: "Standalone, reusable source questions for building exams",
    newQuestion: "New question",
    buildExam: "Build exam",
    buildTitle: "Build an exam from the question bank",
    buildDescription:
      "Review the preview first; questions are only added after explicit confirmation.",
    search: "Search question, subject, topic, or tag",
    noSubject: "No subject",
    edit: "Edit",
    archive: "Archive",
    archiveTitle: "Archive bank question?",
    archiveDescription: "Copies already added to exams or quizzes stay unchanged.",
    none: "No source question matches this search.",
    organization: "Select an organization",
    question: "Question text",
    correctOption: (n: number) => `Correct answer: option ${n}`,
    option: (n: number) => `Option ${n}`,
    subject: "Subject",
    topic: "Topic",
    grade: "Grade",
    chapter: "Chapter",
    lesson: "Lesson",
    tags: "Tags, separated by commas",
    explanation: "Answer explanation (optional)",
    save: "Save question",
    cancel: "Cancel",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    selectExam: "Select a target exam",
    noMatches: "No questions match the selected mix.",
    added: (count: number, skipped: number, locale: string) =>
      `${count.toLocaleString(locale)} questions added to the exam.${skipped ? ` ${skipped.toLocaleString(locale)} duplicate questions skipped.` : ""}`,
    failedBuild: "Could not build the exam from the question bank.",
    preview: (count: number, locale: string) => `Preview ${count.toLocaleString(locale)} questions`,
    confirmAdd: "Confirm and add",
  },
} as const;

export function useQuestionBankCopy() {
  const { language, profile } = useLocale();
  return { ...copy[language], locale: profile.locale };
}
