import type { AdminLanguage } from "../../../shared/ui/locale";

const copy = {
  fa: {
    locale: "fa-IR",
    general: "عمومی",
    resourceUpdated: "منبع به‌روزرسانی شد.",
    resourceCreated: "منبع آموزشی ساخته شد.",
    saveFailed: "ذخیره منبع ناموفق بود.",
    resourceDeleted: "منبع حذف شد.",
    deleteFailed: "حذف منبع ناموفق بود.",
    shared: "منبع برای دانش‌آموز انتخاب‌شده ارسال شد.",
    shareFailed: "اشتراک‌گذاری منبع ناموفق بود.",
    editResource: "ویرایش منبع آموزشی",
    newResource: "منبع آموزشی جدید",
    editorDescription: "مشخصات منبع و دانش‌آموزان دریافت‌کننده را در یک مرحله ثبت کنید.",
    deleteTitle: "حذف منبع آموزشی؟",
    deleteDescription: (title: string) => `«${title}» و تخصیص‌های آن حذف می‌شود.`,
    deleteResource: "حذف منبع",
    noAccess: "دسترسی مدیریت منابع آموزشی ندارید.",
    list: "فهرست منابع",
    listDescription: "نتایج با فیلترهای بالا به‌روزرسانی می‌شوند.",
    noFiltered: "منبعی با این فیلتر نیست.",
    noResources: "هنوز منبعی ساخته نشده است.",
    create: "ساخت منبع",
    new: "جدید",
    search: "جستجوی عنوان یا توضیح",
    results: (count: number) => `${count.toLocaleString("fa-IR")} نتیجه`,
    statusFilter: "فیلتر وضعیت منبع",
    categoryFilter: "فیلتر دسته منبع",
    allStatuses: "همه وضعیت‌ها",
    allCategories: "همه دسته‌ها",
    published: "منتشر",
    draft: "پیش‌نویس",
    archived: "بایگانی",
    detailsView: "نمای ردیفی با جزئیات",
    gridView: "نمای سه‌ستونه",
    prerequisitesFailed: "دریافت فهرست دانش‌آموزان یا کلاس‌ها برای فرم منبع ناموفق بود.",
    retry: "تلاش دوباره",
    title: "عنوان",
    titlePlaceholder: "عنوان کوتاه و روشن",
    link: "پیوند HTTPS",
    type: "نوع",
    video: "ویدئو",
    resourceLink: "پیوند",
    status: "وضعیت",
    category: "دسته‌بندی",
    categoryPlaceholder: "مثلاً مرور، ویدئو، آزمون",
    recipients: "دریافت‌کننده",
    students: (count: number) => `${count.toLocaleString("fa-IR")} دانش‌آموز`,
    description: "توضیح",
    cancel: "انصراف",
    saveChanges: "ذخیره تغییرات",
    createAndAssign: "ساخت و تخصیص",
    noDescription: "بدون توضیح",
    edit: "ویرایش",
    editResourceLabel: (title: string) => `ویرایش منبع ${title}`,
    openResource: "باز کردن منبع",
    updatedAt: "آخرین تغییر",
    recipientsLabel: "دریافت‌کننده",
  },
  en: {
    locale: "en-US",
    general: "General",
    resourceUpdated: "Resource updated.",
    resourceCreated: "Learning resource created.",
    saveFailed: "Could not save the resource.",
    resourceDeleted: "Resource deleted.",
    deleteFailed: "Could not delete the resource.",
    shared: "The resource was sent to the selected student.",
    shareFailed: "Could not share the resource.",
    editResource: "Edit learning resource",
    newResource: "New learning resource",
    editorDescription: "Set the resource details and its student recipients in one step.",
    deleteTitle: "Delete learning resource?",
    deleteDescription: (title: string) => `“${title}” and its assignments will be deleted.`,
    deleteResource: "Delete resource",
    noAccess: "You do not have permission to manage learning resources.",
    list: "Resources",
    listDescription: "Results update as you adjust the filters above.",
    noFiltered: "No resource matches these filters.",
    noResources: "No resources have been created yet.",
    create: "Create resource",
    new: "New",
    search: "Search title or description",
    results: (count: number) => `${count.toLocaleString("en-US")} results`,
    statusFilter: "Resource status filter",
    categoryFilter: "Resource category filter",
    allStatuses: "All statuses",
    allCategories: "All categories",
    published: "Published",
    draft: "Draft",
    archived: "Archived",
    detailsView: "Detailed row view",
    gridView: "Three-column grid view",
    prerequisitesFailed:
      "Could not load the student or class lists required for the resource form.",
    retry: "Try again",
    title: "Title",
    titlePlaceholder: "A short, clear title",
    link: "HTTPS link",
    type: "Type",
    video: "Video",
    resourceLink: "Link",
    status: "Status",
    category: "Category",
    categoryPlaceholder: "For example: review, video, assessment",
    recipients: "Recipients",
    students: (count: number) => `${count.toLocaleString("en-US")} students`,
    description: "Description",
    cancel: "Cancel",
    saveChanges: "Save changes",
    createAndAssign: "Create and assign",
    noDescription: "No description",
    edit: "Edit",
    editResourceLabel: (title: string) => `Edit resource ${title}`,
    openResource: "Open resource",
    updatedAt: "Last updated",
    recipientsLabel: "recipients",
  },
} as const;

export function resourcesCopy(language: AdminLanguage) {
  return copy[language];
}
